---
title: "Setup"
---

### R Settings

* Reuses environment argument `GCE_AUTH_FILE` from googleComputeEngineR which holds location of your service auth JSON
* Reuses environment argument `GCE_DEFAULT_PROJECT_ID` from googleComputeEngineR
* Reuses environment argument `GCS_DEFAULT_BUCKET` from googleCloudStorageR
* New environment argument `CR_REGION` can be one of 

```
"us-central1",
"asia-northeast1",
"europe-west1",
"us-east1"
```
* New environment argument `CR_BUILD_EMAIL` that is your cloudbuild service email

e.g. your `.Renviron` should look like:

```
GCE_AUTH_FILE="/Users/me/auth/auth.json"
GCE_DEFAULT_PROJECT_ID="my-project"
GCS_DEFAULT_BUCKET="my-bucket"
CR_REGION="europe-west1"
CR_BUILD_EMAIL=my-project-number@cloudbuild.gserviceaccount.com
```

You can also set some of the above in the R script via:

* `cr_region_set()`
* `cr_project_set()`
* `cr_bucket_set()`
* `cr_email_set()`

Or auth via

```r
googleAuthR::gar_service_auth("my_auth_json.com")
```

### GCP settings

Its easiest if you create a new service key in your GCP project.

* A service auth key needs Cloud Storage Admin, Cloud Build Editor, Cloud Run Admin, Cloud Scheduler Admin roles to use all the functions in the package - this key can be downloaded and used for auth via `GCE_AUTH_FILE`
* Ensure you have the Cloud Build, Cloud Run, Cloud Storage and Cloud Scheduler APIs on in your GCP project
* The Cloud Build service account needs permissions if you want it to deploy to Cloud Run: This can be set [here](https://console.cloud.google.com/cloud-build/settings) where you enable `Cloud Run Admin` and `Service Account User` roles.  More details found at this [Google reference article](https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-cloud-run). 
* If you get the error using Cloud Scheduler with a HTTP target of "Request contains an invalid argument" then ensure you have a service email with `service-{project-number}@gcp-sa-cloudscheduler.iam.gserviceaccount.com` with Cloud Scheduler Service Agent role.  This is only needed if you created the project before MArch 2019.  This only needs to exist in the GCP project, it is not used in deployment - create another service key for that. See [here](https://cloud.google.com/scheduler/docs/http-target-auth#add)
* If you want to use GitHub or BitBucket repos, you need to setup mirroring them via Cloud Source Repoitories https://source.cloud.google.com/
* To use Cloud Scheduler you may need to initiate an App Engine application https://console.developers.google.com/appengine - you only need to set the region (one allowed per GCP project) and you don't need to create an app


