---
title: "Example Use Cases for googleCloudRunner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example Use Cases for googleCloudRunner}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Here will be some example use cases you can use googleCloudRunner for.

Since almost any code can be called and passed via Docker images, there are a lot of potential uses.

* Scheduling R scripts in the cloud
* R APIs to call from anywhere
* Triggering R code to run on events, such as BigQuery table updates or GitHub pushes
* Checking a package, creating a website, deploying it to GitHub
* Running authenticated tests for R packages in private environment
* Creating an Rmarkdown powered website using Cloud Run
* Integrating R with other language applications
* Public and private Docker image creations on triggers

Some [community contributed Cloud Build images are listed here](https://github.com/GoogleCloudPlatform/cloud-builders-community), including [hugo](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/hugo), [make](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/make), and [tar](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/tar).

## Create Docker image of a package

This is what is used to deploy this package as a Docker image to the public `googleComputeEngineR` docker image project, `gcr.io/gcer-public`

This builds a Docker image of the Dockerfile in the root directory of the GitHub repo, which is then [mirrored to Google Source Repositories](https://cloud.google.com/source-repositories/docs/mirroring-a-github-repository) via the GitHub app. 

```r
my_image <- "gcr.io/my-project/my-image"

# this repo mirrored on Google Source repos
my_repo <- RepoSource("github_markedmondson1234_googlecloudrunner",
                      branchName="master"))

docker_yaml <- cr_build_yaml(steps = cr_buildstep_docker(my_image))

built_docker <- cr_build(docker_yaml, source = my_repo)

# make a build trigger so it builds on each push to master
cr_buildtrigger("build-docker", trigger = my_repo, build = built_docker)
```

## Trigger an R function from pubsub

This uses `cr_deploy_plumber` to deploy an R API that can then be triggered from pub/sub events, such as Cloud logging events or when files get updated in a Cloud Storage bucket.  This in turn can trigger other Cloud Builds. 

A plumber API that accepts pub/sub messages is facilitated by `cr_plumber_pubsub()`

`api.R`:

```r
# example function echos back pubsub message
# change to do something more interesting with event data
pub <- function(x){
  paste("Echo:", x)
}

#' Recieve pub/sub message
#' @post /pubsub
#' @param message a pub/sub message
function(message=NULL){
  googleCloudRunner::cr_plumber_pubsub(message, pub)
}
```

Deploy the R API using an image that has plumber and googleCloudRunner installed.  There is one available at `gcr.io/gcer-public/googlecloudrunner`

`Dockerfile`:

```
FROM gcr.io/gcer-public/googlecloudrunner:master

COPY [".", "./"]

ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(commandArgs()[4]); pr$run(host='0.0.0.0', port=as.numeric(Sys.getenv('PORT')))"]
CMD ["api.R"]
```

Put both the Dockerfile and the `api.R` script in the same folder then deploy it to Cloud Run:

```r
cr_deploy_plumber("the_folder")
```

Once built you will have a pub/sub live that will trigger the function you defined.  You can test pubsub messages via `cr_pubsub()`

```r
test_url <- "http://your-cloudrun-api.com/pubsub"

cr_pubsub(test_url, "hello")
# [1] "Echo: hello"
```

In this case the function only echos, but you can modify the function to call other libraries, functions, operate on data sent in pubsub such as bucket object names, BigQuery tableIds, etc.

```r
# perhaps the function calls another Cloud Build
pub <- function(x){
  cr_build(x, source = my_source)
}
```

## Build and deploy Rmd files to Cloud Run every Git commit

Cloud Run scales from 0 to millions of hits, so can be an option for hosting a website.  In particular you may want a private internal website, or have lots of traffic or data that goes over other free hosting options such as GitHub pages. A nginx server configuration is included to host any HTML you provide via `cr_deploy_html()`.  

Coupled to that, a common use case is to render Rmd files and host them on a website.  

This can be achieved using `cr_deploy_git_html()` which will upon your chosen git event trigger run R code on your markdown files that should create HTML pages, and then deploy those to Cloud Run.

1. Mirror your GitHub/Bitbucket repo to Cloud Repositories
2. Put your markdown files in a directory within your Git repo 
3. Run the below code to setup a build trigger that will render and deploy the markdown files each commit:

```r
your_repo <- "MarkEdmondson1234/googleCloudRunner"
markdown_folder <-  "vignettes"
cr_deploy_git_html(your_repo, rmd_folder = markdown_folder)
```

4. If you want to customise how your markdown is rendered (perhaps using pkgdown to render your package website), supply that code in `edit_r` argument:

```r
your_repo <- "MarkEdmondson1234/googleCloudRunner"
r <- "devtools::install(); pkgdown::build_site()"
cr_deploy_git_html(your_repo, 
                   image = paste0(your_repo, "-pkgdown"), 
                   rmd_folder = ".", edit_r = r)
                   
cr_run_get("markedmondson1234-googlecloudrunner-pkgdown")
#==CloudRunService==
#name:  markedmondson1234-googlecloudrunner-pkgdown 
#location:  europe-west1 
#lastModifier:  1080525199262@cloudbuild.gserviceaccount.com 
#containers:  gcr.io/mark-edmondson-gde/markedmondson1234/googlecloudrunner-pkgdown:20d3e18 
#creationTimestamp:  2019-12-26T19:24:10.789691Z 
#observedGeneration:  1 
#url:  https://markedmondson1234-googlecloudrunner-pkgdown-ewjogewawq-ew.a.run.app 
```

## Polygot Cloud Builds - integrating R code with other languages

Since Docker containers can hold any language within them, they offer a universal UI to combine languages.  This offers opportunities to extend other languages with R features, and give other languages access to R code without needing to know R.

An example below uses:

* `gcloud` - [Google's Cloud command line tool](https://cloud.google.com/sdk/gcloud/) to access Google's key management store and download an authentication file
* `gago` - [A Go package for fast downloads of Google Analytics data](https://github.com/MarkEdmondson1234/gago)
* `R` - R code to create an Rmd file that will hold interactive forecasts of the Google Analytics data via `cr_buildstep_r()`
* `nginx` - serve up the Rmd files rendered into HTML and hosted on Cloud Run via `cr_deploy_html()`


```{r, code=readLines("polygot.R"), eval=FALSE, echo = TRUE}
```

An example of the demo output is on this Cloud Run instance URL:
`https://polygot-demo-ewjogewawq-ew.a.run.app/polygot.html`

This constructed cloud build can also be used outside of R, by writing out the Cloud Build file via `cr_build_write()`

```r
# write out to cloudbuild.yaml for other languages
cr_build_write(polygot)
# 2019-12-28 19:15:50> Writing to cloudbuild.yaml
```

This can also be scheduled as described in Cloud Scheduler section on [scheduled cloud builds](https://code.markedmondson.me/googleCloudRunner/articles/cloudscheduler.html).

An example of that cloudbuild.yaml is on GitHub [here](https://raw.githubusercontent.com/MarkEdmondson1234/googleCloudRunner/master/inst/polygot/cloudbuild.yaml).

## Scheduled update of an RMarkdown dashboard from Google Sheets

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I have a flexdashboard that shows data from a Google Sheet with ggplotly. What&#39;s the best way to host the dashboard somewhere *and* make it so it shows the latest data? i.e. how should I show dynamic data in an RMarkdown dashboard? Continually reknit? Make a plumber API? <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; Andrew Heiss, PhD (@andrewheiss) <a href="https://twitter.com/andrewheiss/status/1212408575684943878?ref_src=twsrc%5Etfw">January 1, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

This tweet came up as I was looking for use cases.  A solution may be to:

* Create a Docker image to knit the Rmd 
* Knit the Rmd dashboard using flexdashboard
* Host the HTML on Cloud Run
* Set up a schedule for the new data in googlesheets

The solution below assumes that the source is available on a public GitHub, but other sources could be also used such as private repos or Cloud Storage.  

For the example below, this repo is used with the source files in `inst/scheduled_rmarkdown`

### Rmd dashboard

The Rmd can run R code downloading the data within it in its setup block - this should mean little changes are needed from the local version.  

#### Authentication in Rmd

One modification could be if you need to read from a private Googlesheet.  See [gargle's guide on what is necessary for non-interactive auth](https://gargle.r-lib.org/articles/non-interactive-auth.html), which could be adding the Cloud Build auth email as a user to the sheet, or setting up decryption of a token via `cr_buildstep_decrypt()`

For the example, a public Google Sheets URL is assumed and auth is avoided by using `googlesheets4::sheets_deauth()` within the Rmd file.

### Docker image
 
 For the Rmd these packages were loaded:
 
```r
library(flexdashboard)
library(googlesheets4)
library(ggplot2)
library(plotly)
library(dplyr)
```

The R image rendering the Rmd needs these libraries and dependencies installed.

This was done using `containerit`, feeding in the Rmd file to autodetect the dependencies:

```r
d <- containerit::dockerfile("inst/scheduled_rmarkdown/scheduled_rmarkdown.Rmd")
containerit::write(d, "inst/scheduled_rmarkdown/Dockerfile")
```

In this case since some tidyverse packages were used, the `FROM` was change to start from `rocker/verse` to speed up the build. 

This dockerfile was then built into an image that will be used to render the Rmd during build steps.  This builds all the libraries from source and places them in a docker R image you can use for future buildsteps - in this case called `gcr.io/my-project/scheduled_rmarkdown:latest`:

```r
library(googleCloudRunner)
cr_deploy_docker("inst/scheduled_rmarkdown/", tag = "latest", timeout = 1200)
```

If there a lot of libraries it may take a while (>20 mins) to build, you can cancel out of the R session awaiting the build and just follow the online logs if you wish.

Once built, you do not need to build it again unless you want to update the R library versions.

### Create the Cloud Build for scheduling

Since we are using a Git repo and are hosting on Cloud Run, `cr_deploy_git_html()` could be used to automate render the Rmd and hosting the HTML via nginx on Cloud Run.

This will make another Docker image that hosts the HTML and deploy it to Cloud Run, and it will also setup a build trigger to rebuild the image if the Rmd changes in future commits. 

```r
cr_deploy_git_html("MarkEdmondson1234/googleCloudRunner",
                   image = "scheduled-rmarkdown-cloudrun",
                   rmd_folder = "inst/scheduled_rmarkdown/",
                   r_image = "gcr.io/my-project/scheduled_rmarkdown:latest")
```

However, since we want to schedule the Cloud Build that renders the Rmd, we will construct our own build using the buildstep templates:

```r
run_image <- "scheduled-rmarkdown-cloudrun"
rmd_folder <- "inst/scheduled_rmarkdown/"
r_image <- "gcr.io/mark-edmondson-gde/scheduled_rmarkdown:latest"

r <- "rmarkdown::render('scheduled_rmarkdown.Rmd')"

# script to setup nginx 
bash_script <- system.file("docker", "nginx", "setup.bash",
                           package = "googleCloudRunner")

repo_name <- paste0("github_markedmondson1234_googlecloudrunner")

repo_source <- cr_build_source(RepoSource(repo_name,
                          branchName = ".*",
                          projectId = cr_project_get()))
                          
build_me <- cr_build_yaml(
      steps = c(
          cr_buildstep_r(r,
                  name = r_image,
                  dir = "inst/scheduled_rmarkdown/",
                  id="render rmd"),
          cr_buildstep_bash(bash_script,
                            dir = "inst/scheduled_rmarkdown/", 
                            id = "setup nginx"),
          cr_buildstep_docker(run_image,
                              tag = "latest",
                              dir = "inst/scheduled_rmarkdown/"),
          cr_buildstep_run(name = "scheduled-rmd",
                  image = "gcr.io/mark-edmondson-gde/scheduled-rmarkdown-cloudrun:latest",
                  concurrency = 80)
          )
    )
    

cr_build(build_me, source = repo_source)
```
