#' Returns information about a `BuildTrigger`.This API is experimental.
#'
#'
#' @param projectId ID of the project that owns the trigger
#' @param triggerId ID of the `BuildTrigger` to get
#' @importFrom googleAuthR gar_api_generator
#' @export
cr_buildtrigger_get <- function(projectId, triggerId) {
    url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s",
        projectId, triggerId)
    # cloudbuild.projects.triggers.get
    f <- gar_api_generator(url,
                           "GET",
                           data_parse_function = function(x) x)
    f()

}

#' Updates a `BuildTrigger` by its project ID and trigger ID.This API is experimental.
#'
#'
#' @param BuildTrigger The \link{BuildTrigger} object to pass to this method
#' @param projectId ID of the project that owns the trigger
#' @param triggerId ID of the `BuildTrigger` to update
#' @importFrom googleAuthR gar_api_generator
#' @family BuildTrigger functions
#' @export
cr_buildtrigger_edit <- function(BuildTrigger, projectId, triggerId) {
    url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s",
        projectId, triggerId)
    # cloudbuild.projects.triggers.patch
    f <- gar_api_generator(url, "PATCH",
                           data_parse_function = function(x) x)
    stopifnot(inherits(BuildTrigger, "gar_BuildTrigger"))

    f(the_body = BuildTrigger)

}

#' Deletes a `BuildTrigger` by its project ID and trigger ID.This API is experimental.
#'
#'
#' @param projectId ID of the project that owns the trigger
#' @param triggerId ID of the `BuildTrigger` to delete
#' @importFrom googleAuthR gar_api_generator
#' @export
cr_buildtrigger_delete <- function(projectId, triggerId) {

    url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s",
        projectId, triggerId)
    # cloudbuild.projects.triggers.delete
    f <- gar_api_generator(url, "DELETE",
                           data_parse_function = function(x) x)
    f()

}

#' Lists existing `BuildTrigger`s.This API is experimental.
#'
#'
#' @param projectId ID of the project for which to list BuildTriggers
#' @param pageToken Token to provide to skip to a particular spot in the list
#' @param pageSize Number of results to return in the list
#' @importFrom googleAuthR gar_api_generator
#' @export
cr_buildtrigger_list <- function(projectId,
                                 pageToken = NULL,
                                 pageSize = NULL){

    url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers",
                   projectId)
    # cloudbuild.projects.triggers.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- gar_api_generator(url, "GET",
                           pars_args = rmNullObs(pars),
                           data_parse_function = function(x) x)
    f()

}

#' Creates a new `BuildTrigger`.This API is experimental.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param BuildTrigger The \link{BuildTrigger} object to pass to this method
#' @param projectId ID of the project for which to configure automatic builds
#' @importFrom googleAuthR gar_api_generator
#' @family BuildTrigger functions
#' @export
cr_buildtrigger <- function(BuildTrigger, projectId) {

    url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers",
                   projectId)
    # cloudbuild.projects.triggers.create
    f <- gar_api_generator(url, "POST",
                           data_parse_function = function(x) x)
    stopifnot(inherits(BuildTrigger, "gar_BuildTrigger"))

    f(the_body = BuildTrigger)

}

#' Runs a `BuildTrigger` at a particular source revision.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param RepoSource The \link{RepoSource} object to pass to this method
#' @param projectId ID of the project
#' @param triggerId ID of the trigger
#' @importFrom googleAuthR gar_api_generator
#' @family RepoSource functions
#' @export
cr_buildtrigger_run <- function(RepoSource, projectId, triggerId){

    url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s:run",
        projectId, triggerId)

    # cloudbuild.projects.triggers.run
    f <- gar_api_generator(url, "POST",
                           data_parse_function = function(x) x)
    stopifnot(inherits(RepoSource, "gar_RepoSource"))

    f(the_body = RepoSource)

}

#' GitHubEventsConfig Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' GitHubEventsConfig describes the configuration of a trigger that creates abuild whenever a GitHub event is received.This message is experimental.
#'
#' @param pullRequest filter to match changes in pull requests
#' @param push filter to match changes in refs like branches, tags
#' @param installationId The installationID that emits the GitHub event
#' @param owner Owner of the repository
#' @param name Name of the repository
#'
#' @return GitHubEventsConfig object
#'
#' @family GitHubEventsConfig functions
#' @export
GitHubEventsConfig <- function(pullRequest = NULL,
                               push = NULL,
                               installationId = NULL,
                               owner = NULL,
                               name = NULL) {

    structure(rmNullObs(list(pullRequest = pullRequest,
                   push = push,
                   installationId = installationId,
                   owner = owner,
                   name = name),
              class = list("gar_GitHubEventsConfig","list")))
}

#' BuildTrigger Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Configuration for an automated build in response to source repositorychanges.
#'
#' @param BuildTrigger.substitutions The \link{BuildTrigger.substitutions} object or list of objects
#' @param filename Path, from the source root, to a file whose contents is used for the
#' @param name User assigned name of the trigger
#' @param id Output only
#' @param tags Tags for annotation of a `BuildTrigger`
#' @param build Contents of the build template
#' @param ignoredFiles ignored_files and included_files are file glob matches using
#' @param github GitHubEventsConfig describes the configuration of a trigger that creates
#' @param substitutions Substitutions data for Build resource
#' @param includedFiles If any of the files altered in the commit pass the ignored_files
#' @param disabled If true, the trigger will never result in a build
#' @param createTime Output only
#' @param triggerTemplate Template describing the types of source changes to trigger a build
#' @param description Human-readable description of this trigger
#'
#' @return BuildTrigger object
#'
#' @family BuildTrigger functions
#' @export
BuildTrigger <- function(BuildTrigger.substitutions = NULL,
                         filename = NULL,
                         name = NULL,
                         id = NULL,
                         tags = NULL,
                         build = NULL,
                         ignoredFiles = NULL,
                         github = NULL,
                         substitutions = NULL,
                         includedFiles = NULL,
                         disabled = NULL,
                         createTime = NULL,
                         triggerTemplate = NULL,
                         description = NULL) {

    structure(rmNullObs(list(BuildTrigger.substitutions = BuildTrigger.substitutions,
                   filename = filename,
                   name = name,
                   id = id,
                   tags = tags,
                   build = build,
                   ignoredFiles = ignoredFiles,
                   github = github,
                   substitutions = substitutions,
                   includedFiles = includedFiles,
                   disabled = disabled,
                   createTime = createTime,
                   triggerTemplate = triggerTemplate,
                   description = description),
                   class = c("gar_BuildTrigger","list")))
}
