#' @title Set up Google Cloud Build to run a targets pipeline
#' @export
#' @family Cloud Build functions
#' @description Creates a Google Cloud Build yaml file so as to execute \link[targets]{tar_make} pipelines
#'
#' Historical runs accumulate in the
#'   configured Google Cloud Storage bucket, and the latest output is downloaded before
#'   \link[targets]{tar_make} executes so up-to-date steps do not rerun.
#' @details Steps to set up your target task in Cloud Build:
#'
#' \itemize{
#'   \item Create your `targets` workflow.
#'   \item Create a Dockerfile that holds the R and system dependencies for your workflow.  You can test the image using \link{cr_deploy_docker()}.  Include \code{library(targets)} dependencies - a Docker image with \code{targets} installed is available at \code{gcr.io/gcer-public/targets}.
#'   \item Run \code{cr_build_targets()} to create the cloudbuild yaml file.
#'   \item Create a build trigger via \link{cr_buildtrigger}.
#'   \item Trigger a build. The first trigger will run the targets pipeline, subsequent runs will only recompute the outdated targets.
#'  }
#'
#' @return A Yaml object as generated by \link{cr_build_yaml}
#' @param path File path to write the Google Cloud Build yaml workflow file. Set to NULL to write no file and just return the \link{Yaml} object.
#' @param task_image An existing Docker image that will be used to run your targets workflow after the targets meta has been downloaded from Google Cloud Storage
#' @param target_folder Where target metadata will sit within the Google Cloud Storage bucket as a folder.  Defaults to RStudio project name.
#' @param bucket The Google Cloud Storage bucket the target metadata will be saved to in folder `target_folder`
#' @param ... Other arguments passed to \link{cr_build_yaml()}
#' @inheritDotParams cr_build_yaml
#' @param task_args A named list of additional arguments to send to \link{cr_buildstep_r()} when its executing the \link[targets]{tar_make()} command (such as environment arguments)
#' @param tar_make The R script that will run in the tar_make() step. Modify to include custom settings such as "script"
#'
#' @examples
#'
#' cr_build_targets(path=tempfile())
#'
#' # adding custom environment args and secrets to the build
#' cr_build_targets(
#'   task_image = "gcr.io/my-project/my-targets-pipeline",
#'   options = list(env = c("ENV1=1234",
#'                          "ENV_USER=Dave")),
#'   availableSecrets = cr_build_yaml_secrets("MY_PW","my-pw"),
#'   task_args = list(secretEnv = "MY_PW"))
#'
cr_build_targets <- function(
  task_image = "gcr.io/gcer-public/targets",
  target_folder = basename(rstudioapi::getActiveProject()),
  path = "cloudbuild_targets.yaml",
  bucket = cr_bucket_get(),
  task_args = list(),
  tar_make = c("list.files(recursive=TRUE)","targets::tar_make()"),
  ...
) {

  if(is.null(target_folder)){
    target_folder <- "targets_cloudbuild"
  }

  myMessage(sprintf("targets metadata: gs://%s/%s", bucket, target_folder),
            level = 3)

  target_metadata <- paste0(target_folder, "/_targets")

  bs <- c(
    cr_buildstep_bash(
      "gsutil mv ${_TARGET_BUCKET}/meta/artifacts- ${_TARGET_BUCKET}/artifacts/artifacts- || exit 0",
      name = "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine",
      entrypoint = "bash",
      escape_dollar = FALSE,
      id = "move old artifact files if present"
    ),
    cr_buildstep_bash(
      "mkdir /workspace/_targets && gsutil -m cp -r ${_TARGET_BUCKET}/meta/* /workspace/_targets/meta || exit 0",
      name = "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine",
      entrypoint = "bash",
      escape_dollar = FALSE,
      id = "get previous _targets metadata"
    ),
    do.call(
      cr_buildstep_r,
      args = c(task_args,
               list(r =tar_make,
                    name = task_image,
                    id = "target pipeline"))
    )
  )

  target_bucket <- sprintf("gs://%s/%s", bucket, target_metadata)

  yaml <- cr_build_yaml(
    bs,
    substitutions = list(`_TARGET_BUCKET` = target_bucket),
    artifacts = cr_build_yaml_artifact("/workspace/_targets/**",
                                       bucket_dir = target_metadata,
                                       bucket = bucket),
    timeout = 3600,
    ...
  )

  if(!is.null(path)) cr_build_write(yaml, file = path)

  yaml
}

#' @rdname cr_build_targets
#' @export
#' @details
#'   Use \code{cr_build_targets_artifacts} to download the return values of a
#'   target Cloud Build, then \link[targets]{tar_read} to read the results
#' @inheritParams cr_build_artifacts
cr_build_targets_artifacts <- function(
  build,
  download_folder= "_targets_cloudbuild",
  overwrite = overwrite){

  bb <- build$source$storageSource$bucket
  if(is.null(bb)){
    stop("Could not find bucket.  Is this not a build from cr_build_targets()?")
  }

  build_folder <- gsub("gs://(.+)/(.+)/_targets/meta","\\2",build$artifacts$objects$location)

  arts <- googleCloudStorageR::gcs_list_objects(
    bucket = bb, prefix = build_folder
  )

  dir.create(download_folder, showWarnings = FALSE)

  lapply(arts$name, function(x) {
    gcs_get_object(x, bucket = bb, saveToDisk = file.path(download_folder, x))
    })
}
