#' Starts a build with the specified configuration.
#'
#' This method returns a long-running `Operation`, which includes the buildID. Pass the build ID to \link{cr_build_status} to determine the build status (such as `SUCCESS` or `FAILURE`).
#'
#'
#' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation for Cloud Build}
#'
#' @inheritParams Build
#' @param projectId ID of the project
#' @param yaml A cloudbuild.yaml with the steps to run for the build - either a file location or a yaml string produced by \link[yaml]{as.yaml}
#' @importFrom googleAuthR gar_api_generator
#' @importFrom yaml yaml.load_file
#' @import assertthat
#' @family Build functions
#' @export
#' @examples
#'
#' \dontrun{
#'
#' cr_init()
#' b1 <- cr_build("cloudbuild.yaml")
#' b2 <- cr_build_wait(b1)
#' cr_build_status(b1)
#' cr_build_status(b2)
#'
#' }
cr_build <- function(yaml,
                     timeout=NULL,
                     images=NULL,
                     projectId = Sys.getenv("GCE_DEFAULT_PROJECT_ID")) {

  url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds",
                 projectId)

  stepsy <- get_cr_yaml(yaml)
  if(is.null(stepsy$steps)){
    stop("Invalid cloudbuild yaml - 'steps:' not found.", call. = FALSE)
  }
  build <- Build(steps = stepsy$steps,
                 timeout = timeout,
                 images = images)

  # cloudbuild.projects.builds.create
  f <- gar_api_generator(url, "POST",
        data_parse_function = function(x) structure(x,
                                           class = "BuildOperationMetadata"))
  stopifnot(inherits(build, "gar_Build"))

  o <- f(the_body = build)

  myMessage("Cloud Build started - logs: \n", o$metadata$build$logUrl,
            level = 3)

  invisible(o)
}

is.BuildOperationMetadata <- function(x){
  inherits(x, "BuildOperationMetadata")
}

#' Returns information about a previously requested build.
#'
#' The `Build` that is returned includes its status (such as `SUCCESS`,`FAILURE`, or `WORKING`), and timing information.
#'
#'
#' @param projectId ID of the project
#' @param id ID of the build or a \code{BuildOperationMetadata} object
#' @importFrom googleAuthR gar_api_generator
#' @import assertthat
#' @export
cr_build_status <- function(id,
                            projectId = Sys.getenv("GCE_DEFAULT_PROJECT_ID")){

  the_id <- extract_build_id(id)

  url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds/%s",
                 projectId, the_id)
  # cloudbuild.projects.builds.get
  f <- gar_api_generator(url, "GET",
          data_parse_function = function(x) as.gar_Build(x))
  f()

}

#' Wait for a Build to run
#'
#' This will repeatedly call \link{cr_build_status} whilst the status is STATUS_UNKNOWN, QUEUED or WORKING
#'
#' @param op The operation build object to wait for
#' @param projectId The projectId
#' @export
cr_build_wait <- function(op = .Last.value,
                          projectId = Sys.getenv("GCE_DEFAULT_PROJECT_ID")){

  the_id <- extract_build_id(op)

  wait_for <- c("STATUS_UNKNOWN", "QUEUED", "WORKING")

  init <- cr_build_status(the_id, projectId = projectId)
  if(!init$status %in% wait_for){
    return(init)
  }

  cat("\nWaiting for build to finish:\n")
  print(init)

  op <- init
  wait <- TRUE
  while(wait){
    status <- cr_build_status(op, projectId = projectId)
    if(!status$status %in% wait_for){
      wait <- FALSE
    }
    op <- status
    Sys.sleep(5)
  }

  cat("\nBuild finished")
  status
}

extract_build_id <- function(op){
  if(is.BuildOperationMetadata(op)){
    the_id <- op$metadata$build$id
  } else if (is.gar_Build(op)){
    the_id <- op$id
  } else {
    assert_that(is.string(op))
    the_id <- op
  }

  the_id
}

as.gar_Build <- function(x){
  class(x) <- c("gar_Build", class(x))
  x
}

is.gar_Build <- function(x){
  inherits(x, "gar_Build")
}

#' Build Object
#'
#' @details
#' A build resource in the Cloud Build API.At a high level, a `Build` describes where to find source code, how to buildit (for example, the builder image to run on the source), and where to storethe built artifacts.
#' Fields can include the following variables, which will be expanded when the build is created:- $PROJECT_ID: the project ID of the build.- $BUILD_ID: the autogenerated ID of the build.- $REPO_NAME: the source repository name specified by RepoSource.- $BRANCH_NAME: the branch name specified by RepoSource.- $TAG_NAME: the tag name specified by RepoSource.- $REVISION_ID or $COMMIT_SHA: the commit SHA specified by RepoSource or  resolved from the specified branch or tag.- $SHORT_SHA: first 7 characters of $REVISION_ID or $COMMIT_SHA.
#'
#' @param Build.substitutions The \link{Build.substitutions} object or list of objects
#' @param Build.timing The \link{Build.timing} object or list of objects
#' @param results Output only
#' @param logsBucket Google Cloud Storage bucket where logs should be written (see
#' @param steps Required
#' @param buildTriggerId Output only
#' @param id Output only
#' @param tags Tags for annotation of a `Build`
#' @param startTime Output only
#' @param substitutions Substitutions data for `Build` resource
#' @param timing Output only
#' @param sourceProvenance Output only
#' @param createTime Output only
#' @param images A list of images to be pushed upon the successful completion of all build
#' @param projectId Output only
#' @param logUrl Output only
#' @param finishTime Output only
#' @param source The location of the source files to build
#' @param options Special options for this build
#' @param timeout Amount of time that this build should be allowed to run, to second
#' @param status Output only
#' @param statusDetail Output only
#' @param artifacts Artifacts produced by the build that should be uploaded upon
#' @param secrets Secrets to decrypt using Cloud Key Management Service
#'
#' @return Build object
#'
#' @family Build functions
#' @export
Build <- function(Build.substitutions = NULL,
                  Build.timing = NULL,
                  results = NULL,
                  logsBucket = NULL,
                  steps = NULL,
                  buildTriggerId = NULL,
                  id = NULL,
                  tags = NULL,
                  startTime = NULL,
                  substitutions = NULL,
                  timing = NULL,
                  sourceProvenance = NULL,
                  createTime = NULL,
                  images = NULL,
                  projectId = NULL,
                  logUrl = NULL,
                  finishTime = NULL,
                  source = NULL,
                  options = NULL,
                  timeout = NULL,
                  status = NULL,
                  statusDetail = NULL,
                  artifacts = NULL,
                  secrets = NULL) {

  structure(list(Build.substitutions = Build.substitutions,
                 Build.timing = Build.timing,
                 results = results,
                 logsBucket = logsBucket,
                 steps = steps,
                 buildTriggerId = buildTriggerId,
                 id = id,
                 tags = tags,
                 startTime = startTime,
                 substitutions = substitutions,
                 timing = timing,
                 sourceProvenance = sourceProvenance,
                 createTime = createTime,
                 images = images,
                 projectId = projectId,
                 logUrl = logUrl,
                 finishTime = finishTime,
                 source = source,
                 options = options,
                 timeout = timeout,
                 status = status,
                 statusDetail = statusDetail,
                 artifacts = artifacts,
                 secrets = secrets),
            class = c("gar_Build", "list"))
}