#' Starts a build with the specified configuration.
#'
#' This method returns a long-running `Operation`, which includes the buildID. Pass the build ID to `GetBuild` to determine the build status (such as`SUCCESS` or `FAILURE`).
#'
#'
#' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#'
#' @inheritParams Build
#' @param projectId ID of the project
#' @param yaml A cloudbuild.yaml with the steps to run for the build
#' @importFrom googleAuthR gar_api_generator
#' @importFrom yaml yaml.load_file
#' @import assertthat
#' @family Build functions
#' @export
cr_build <- function(yaml,
                     timeout=NULL,
                     images=NULL,
                     projectId = Sys.getenv("GCE_DEFAULT_PROJECT_ID")) {

  assert_that(
    is.readable(yaml)
  )
  url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds",
                 projectId)

  stepsy <- yaml::yaml.load_file(yaml)
  build <- Build(steps = stepsy$steps,
                 timeout = timeout,
                 images = images)

  # cloudbuild.projects.builds.create
  f <- gar_api_generator(url, "POST", data_parse_function = function(x) x)
  stopifnot(inherits(build, "gar_Build"))

  o <- f(the_body = build)

  myMessage("Cloud Build started - logs: \n", o$metadata$build$logUrl, level = 3)

  invisible(o)
}





#' Build Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A build resource in the Cloud Build API.At a high level, a `Build` describes where to find source code, how to buildit (for example, the builder image to run on the source), and where to storethe built artifacts.
#' Fields can include the following variables, which will be expanded when thebuild is created:- $PROJECT_ID: the project ID of the build.- $BUILD_ID: the autogenerated ID of the build.- $REPO_NAME: the source repository name specified by RepoSource.- $BRANCH_NAME: the branch name specified by RepoSource.- $TAG_NAME: the tag name specified by RepoSource.- $REVISION_ID or $COMMIT_SHA: the commit SHA specified by RepoSource or  resolved from the specified branch or tag.- $SHORT_SHA: first 7 characters of $REVISION_ID or $COMMIT_SHA.
#'
#' @param Build.substitutions The \link{Build.substitutions} object or list of objects
#' @param Build.timing The \link{Build.timing} object or list of objects
#' @param results Output only
#' @param logsBucket Google Cloud Storage bucket where logs should be written (see
#' @param steps Required
#' @param buildTriggerId Output only
#' @param id Output only
#' @param tags Tags for annotation of a `Build`
#' @param startTime Output only
#' @param substitutions Substitutions data for `Build` resource
#' @param timing Output only
#' @param sourceProvenance Output only
#' @param createTime Output only
#' @param images A list of images to be pushed upon the successful completion of all build
#' @param projectId Output only
#' @param logUrl Output only
#' @param finishTime Output only
#' @param source The location of the source files to build
#' @param options Special options for this build
#' @param timeout Amount of time that this build should be allowed to run, to second
#' @param status Output only
#' @param statusDetail Output only
#' @param artifacts Artifacts produced by the build that should be uploaded upon
#' @param secrets Secrets to decrypt using Cloud Key Management Service
#'
#' @return Build object
#'
#' @family Build functions
#' @export
Build <- function(Build.substitutions = NULL,
                  Build.timing = NULL,
                  results = NULL,
                  logsBucket = NULL,
                  steps = NULL,
                  buildTriggerId = NULL,
                  id = NULL,
                  tags = NULL,
                  startTime = NULL,
                  substitutions = NULL,
                  timing = NULL,
                  sourceProvenance = NULL,
                  createTime = NULL,
                  images = NULL,
                  projectId = NULL,
                  logUrl = NULL,
                  finishTime = NULL,
                  source = NULL,
                  options = NULL,
                  timeout = NULL,
                  status = NULL,
                  statusDetail = NULL,
                  artifacts = NULL,
                  secrets = NULL) {

  structure(list(Build.substitutions = Build.substitutions,
                 Build.timing = Build.timing,
                 results = results,
                 logsBucket = logsBucket,
                 steps = steps,
                 buildTriggerId = buildTriggerId,
                 id = id,
                 tags = tags,
                 startTime = startTime,
                 substitutions = substitutions,
                 timing = timing,
                 sourceProvenance = sourceProvenance,
                 createTime = createTime,
                 images = images,
                 projectId = projectId,
                 logUrl = logUrl,
                 finishTime = finishTime,
                 source = source,
                 options = options,
                 timeout = timeout,
                 status = status,
                 statusDetail = statusDetail,
                 artifacts = artifacts,
                 secrets = secrets),
            class = c("gar_Build", "list"))
}