#' Creates a Cloud Scheduler job.
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @inheritParams Job
#' @param projectId The GCP project to run within
#'
#' @importFrom googleAuthR gar_api_generator
#' @family Job functions
#' @export
cr_schedule <- function(schedule,
                        name=NULL,
                        httpTarget=NULL,
                        description=NULL,
                        projectId = Sys.getenv("GCE_DEFAULT_PROJECT_ID")
                        ) {

  url <- sprintf("https://cloudscheduler.googleapis.com/v1/%s/jobs", projectId)

  job <- Job(schedule=schedule,
             name = name,
             httpTarget = httpTarget,
             description = description)

  # cloudscheduler.projects.locations.jobs.create
  f <- gar_api_generator(url, "POST",
                         data_parse_function = function(x) x)
  stopifnot(inherits(job, "gar_Job"))

  f(the_body = job)

}

#' Job Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Configuration for a job.The maximum allowed size for a job is 100KB.
#'
#' @param attemptDeadline The deadline for job attempts
#' @param pubsubTarget Pub/Sub target
#' @param httpTarget HTTP target
#' @param timeZone Specifies the time zone to be used in interpreting
#' @param description Optionally caller-specified in CreateJob or
#' @param appEngineHttpTarget App Engine HTTP target
#' @param status Output only
#' @param retryConfig Settings that determine the retry behavior
#' @param state Output only
#' @param name Optionally caller-specified in CreateJob, after
#' @param lastAttemptTime Output only
#' @param scheduleTime Output only
#' @param schedule Required, except when used with UpdateJob
#' @param userUpdateTime Output only
#'
#' @return Job object
#'
#' @family Job functions
#' @export
Job <- function(attemptDeadline = NULL, pubsubTarget = NULL, httpTarget = NULL, timeZone = NULL,
                description = NULL, appEngineHttpTarget = NULL, status = NULL, retryConfig = NULL,
                state = NULL, name = NULL, lastAttemptTime = NULL, scheduleTime = NULL, schedule = NULL,
                userUpdateTime = NULL) {
  structure(list(attemptDeadline = attemptDeadline, pubsubTarget = pubsubTarget,
                 httpTarget = httpTarget, timeZone = timeZone, description = description,
                 appEngineHttpTarget = appEngineHttpTarget, status = status, retryConfig = retryConfig,
                 state = state, name = name, lastAttemptTime = lastAttemptTime, scheduleTime = scheduleTime,
                 schedule = schedule, userUpdateTime = userUpdateTime),
            class = c("gar_Job","list"))
}

