


#' Create a service.
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation for Cloud Run}
#'
#' @inheritParams ObjectMeta
#' @inheritParams RevisionSpec
#' @inheritParams Container
#' @param projectId The GCP project from which the services should be listed
#' @importFrom googleAuthR gar_api_generator
#' @family Service functions
#' @export
#' @examples
#'
#' \dontrun{
#' cr_region_set("europe-west1")
#' cr_run("gcr.io/my-project/my-image")
#'
#' }
cr_run <- function(image,
                   name = image,
                   concurrency = 1,
                   projectId = Sys.getenv("GCE_DEFAULT_PROJECT_ID")) {

  url <- make_endpoint(projectId)

  service <- Service(
  #  apiVersion = "serving.knative.dev/v1",
    spec = list(
      template = list(
        spec = RevisionSpec(
          containerConcurrency = concurrency,
          containers = Container(
            image = image
          )
        )
      )
    ),
    metadata = ObjectMeta(
      name = name,
      namespace = projectId
    )
  )

  # run.namespaces.services.create
  f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
  stopifnot(inherits(service, "gar_Service"))

  f(the_body = service)

}


#' List CloudRun services.
#'
#'
#' @seealso \href{https://cloud.run}{Google Documentation for Cloud Run}
#'
#' @details
#'
#' @param projectId The GCP project from which the services should be listed
#' @param labelSelector Allows to filter resources based on a label
#' @param limit The maximum number of records that should be returned
#' @importFrom googleAuthR gar_api_generator
#' @export
cr_run_list <- function(projectId = Sys.getenv("GCE_DEFAULT_PROJECT_ID"),
                        labelSelector = NULL,
                        limit = NULL) {

  url <- make_endpoint(projectId)
  # run.namespaces.services.list
  #TODO: paging
  #pars = list(labelSelector = labelSelector, continue = NULL, limit = limit)
  f <- gar_api_generator(url,
                         "GET",
                         pars = NULL,
                         data_parse_function = parse_service_list,
                         checkTrailingSlash=FALSE)
  f()

}

#' @noRd
#' @import assertthat
parse_service_list <- function(x){
  assert_that(
    x$kind == "ServiceList"
  )

  structure(
    x$items,
    class = c(x$kind, "data.frame"))

}

#' Service Object
#'
#' @details
#' Service acts as a top-level container that manages a set of Routes andConfigurations which implement a network service. Service exists to provide asingular abstraction which can be access controlled, reasoned about, andwhich encapsulates software lifecycle decisions such as rollout policy andteam resource ownership. Service acts only as an orchestrator of theunderlying Routes and Configurations (much as a kubernetes Deploymentorchestrates ReplicaSets).The Service's controller will track the statuses of its owned Configurationand Route, reflecting their statuses and conditions as its own.See also:https://github.com/knative/serving/blob/master/docs/spec/overview.md#service
#'
#' @param status Status communicates the observed state of the Service (output only)
#' @param apiVersion The API version for this call such as 'serving
#' @param spec Spec holds the desired state of the Service (from the client)
#' @param metadata Metadata associated with this Service, including name, namespace, labels,
#'
#' @return Service object
#'
#' @family Service functions
Service <- function(status = NULL, apiVersion = NULL, spec = NULL, metadata = NULL) {
  structure(rmNullObs(list(status = status, kind = "Service", apiVersion = apiVersion, spec = spec,
                 metadata = metadata)), class = c("gar_Service","list"))
}

#' ObjectMeta Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta is metadata that allpersisted resources must have, which includes all objects users must create.
#'
#' @param ObjectMeta.labels The \link{ObjectMeta.labels} object or list of objects
#' @param ObjectMeta.annotations The \link{ObjectMeta.annotations} object or list of objects
#' @param creationTimestamp (Optional)
#' @param labels (Optional)
#' @param generation (Optional)
#' @param resourceVersion (Optional)
#' @param selfLink (Optional)
#' @param uid (Optional)
#' @param namespace Namespace defines the space within each name must be unique, within a
#' @param annotations (Optional)
#' @param generateName (Optional)
#' @param clusterName (Optional)
#' @param deletionGracePeriodSeconds (Optional)
#' @param name Name must be unique within a namespace, within a Cloud Run region
#' @param finalizers (Optional)
#' @param deletionTimestamp (Optional)
#' @param ownerReferences (Optional)
#'
#' @return ObjectMeta object
#'
#' @family ObjectMeta functions
ObjectMeta <- function(ObjectMeta.labels = NULL,
                       ObjectMeta.annotations = NULL,
                       creationTimestamp = NULL,
                       labels = NULL,
                       generation = NULL,
                       resourceVersion = NULL,
                       selfLink = NULL,
                       uid = NULL,
                       namespace = NULL,
                       annotations = NULL,
                       generateName = NULL,
                       clusterName = NULL,
                       deletionGracePeriodSeconds = NULL,
                       name = NULL,
                       finalizers = NULL,
                       deletionTimestamp = NULL,
                       ownerReferences = NULL) {
  structure(rmNullObs(list(ObjectMeta.labels = ObjectMeta.labels,
                 ObjectMeta.annotations = ObjectMeta.annotations,
                 creationTimestamp = creationTimestamp,
                 labels = labels,
                 generation = generation,
                 resourceVersion = resourceVersion,
                 selfLink = selfLink,
                 uid = uid,
                 namespace = namespace,
                 annotations = annotations,
                 generateName = generateName,
                 clusterName = clusterName,
                 deletionGracePeriodSeconds = deletionGracePeriodSeconds,
                 name = name,
                 finalizers = finalizers,
                 deletionTimestamp = deletionTimestamp,
                 ownerReferences = ownerReferences)),
            class = c("gar_ObjectMeta","list"))
}

#' RevisionSpec Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' RevisionSpec holds the desired state of the Revision (from the client).
#'
#' @param timeoutSeconds TimeoutSeconds holds the max duration the instance is allowed for
#' @param serviceAccountName Email address of the IAM service account associated with the revision
#' @param containers Containers holds the single container that defines the unit of execution
#' @param volumes No description
#' @param containerConcurrency (Optional)
#'
#' @return RevisionSpec object
#'
#' @family RevisionSpec functions
RevisionSpec <- function(timeoutSeconds = NULL,
                         serviceAccountName = NULL,
                         containers = NULL,
                         volumes = NULL,
                         containerConcurrency = NULL) {
  structure(rmNullObs(list(timeoutSeconds = timeoutSeconds,
                 serviceAccountName = serviceAccountName,
                 containers = containers,
                 volumes = volumes,
                 containerConcurrency = containerConcurrency)),
            class = c("gar_RevisionSpec","list"))
}

#' Container Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A single application container.This specifies both the container to run, the command to run in the containerand the arguments to supply to it.Note that additional arguments may be supplied by the system to the containerat runtime.
#'
#' @param volumeMounts (Optional)
#' @param ports (Optional)
#' @param args (Optional)

#' @param workingDir (Optional)
#' @param envFrom (Optional)
#' @param image Cloud Run fully managed: only supports containers from Google Container Registry
#' @param name (Optional)
#' @param command No description
#' @param terminationMessagePolicy (Optional)
#' @param securityContext (Optional)
#' @param livenessProbe (Optional)
#' @param env (Optional)
#' @param imagePullPolicy (Optional)
#' @param readinessProbe (Optional)
#' @param resources (Optional)
#' @param terminationMessagePath (Optional)
#'
#' @return Container object
#'
#' @family Container functions
Container <- function(volumeMounts = NULL,
                      ports = NULL,
                      args = NULL,
                      workingDir = NULL,
                      envFrom = NULL,
                      image = NULL,
                      name = NULL,
                      command = NULL,
                      terminationMessagePolicy = NULL,
                      securityContext = NULL,
                      livenessProbe = NULL,
                      env = NULL,
                      imagePullPolicy = NULL,
                      readinessProbe = NULL,
                      resources = NULL,
                      terminationMessagePath = NULL) {

  if(!is.null(image)){
    if(!grepl("^gcr.io", image)){
      stop("Only images from Google Container Registry supported e.g. starts with gcr.io",
           call. = FALSE)
    }
  }

  structure(rmNullObs(list(volumeMounts = volumeMounts,
                 ports = ports,
                 args = args,
                 workingDir = workingDir,
                 envFrom = envFrom,
                 image = image,
                 name = name,
                 command = command,
                 terminationMessagePolicy = terminationMessagePolicy,
                 securityContext = securityContext,
                 livenessProbe = livenessProbe,
                 env = env,
                 imagePullPolicy = imagePullPolicy,
                 readinessProbe = readinessProbe,
                 resources = resources,
                 terminationMessagePath = terminationMessagePath)),
            class = c("gar_Container","list"))


}

