#' #' Cloud Build API
#' #' Creates and manages builds on Google Cloud Platform.
#' #'
#' #' Auto-generated code by googleAuthR::gar_create_api_skeleton
#' #'  at 2019-11-03 21:21:25
#' #' filename: R/funcs_build.R
#' #' api_json: build
#' #'
#' #' @details
#' #' Authentication scopes used are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' @docType package
#' #' @name cloudbuild_googleAuthR
#' #'
#' NULL
#' ## NULL
#'
#' #' A helper function that tests whether an object is either NULL _or_
#' #' a list of NULLs
#' #'
#' #' @keywords internal
#' is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' #' Recursively step down into list, removing all such objects
#' #'
#' #' @keywords internal
#' rmNullObs <- function(x) {
#'     x <- Filter(Negate(is.NullOb), x)
#'     lapply(x, function(x) if (is.list(x))
#'         rmNullObs(x) else x)
#' }
#'
#' #' Starts a build with the specified configuration.This method returns a long-running `Operation`, which includes the buildID. Pass the build ID to `GetBuild` to determine the build status (such as`SUCCESS` or `FAILURE`).
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param Build The \link{Build} object to pass to this method
#' #' @param projectId ID of the project
#' #' @importFrom googleAuthR gar_api_generator
#' #' @family Build functions
#' #' @export
#' projects.builds.create <- function(Build, projectId) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds", projectId)
#'     # cloudbuild.projects.builds.create
#'     f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
#'     stopifnot(inherits(Build, "gar_Build"))
#'
#'     f(the_body = Build)
#'
#' }
#'
#' #' Cancels a build in progress.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param CancelBuildRequest The \link{CancelBuildRequest} object to pass to this method
#' #' @param projectId ID of the project
#' #' @param id ID of the build
#' #' @importFrom googleAuthR gar_api_generator
#' #' @family CancelBuildRequest functions
#' #' @export
#' projects.builds.cancel <- function(CancelBuildRequest, projectId, id) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds/%s:cancel",
#'         projectId, id)
#'     # cloudbuild.projects.builds.cancel
#'     f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
#'     stopifnot(inherits(CancelBuildRequest, "gar_CancelBuildRequest"))
#'
#'     f(the_body = CancelBuildRequest)
#'
#' }
#'
#' #' Creates a new build based on the specified build.This method creates a new build using the original build request, which mayor may not result in an identical build.For triggered builds:* Triggered builds resolve to a precise revision; therefore a retry of atriggered build will result in a build that uses the same revision.For non-triggered builds that specify `RepoSource`:* If the original build built from the tip of a branch, the retried buildwill build from the tip of that branch, which may not be the same revisionas the original build.* If the original build specified a commit sha or revision ID, the retriedbuild will use the identical source.For builds that specify `StorageSource`:* If the original build pulled source from Google Cloud Storage withoutspecifying the generation of the object, the new build will use the currentobject, which may be different from the original build source.* If the original build pulled source from Cloud Storage and specified thegeneration of the object, the new build will attempt to use the sameobject, which may or may not be available depending on the bucket'slifecycle management settings.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param RetryBuildRequest The \link{RetryBuildRequest} object to pass to this method
#' #' @param projectId ID of the project
#' #' @param id Build ID of the original build
#' #' @importFrom googleAuthR gar_api_generator
#' #' @family RetryBuildRequest functions
#' #' @export
#' projects.builds.retry <- function(RetryBuildRequest, projectId, id) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds/%s:retry",
#'         projectId, id)
#'     # cloudbuild.projects.builds.retry
#'     f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
#'     stopifnot(inherits(RetryBuildRequest, "gar_RetryBuildRequest"))
#'
#'     f(the_body = RetryBuildRequest)
#'
#' }
#'
#' #' Returns information about a previously requested build.The `Build` that is returned includes its status (such as `SUCCESS`,`FAILURE`, or `WORKING`), and timing information.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param projectId ID of the project
#' #' @param id ID of the build
#' #' @importFrom googleAuthR gar_api_generator
#' #' @export
#' projects.builds.get <- function(projectId, id) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds/%s",
#'         projectId, id)
#'     # cloudbuild.projects.builds.get
#'     f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
#'     f()
#'
#' }
#'
#' #' Lists previously requested builds.Previously requested builds may still be in-progress, or may have finishedsuccessfully or unsuccessfully.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param projectId ID of the project
#' #' @param pageToken Token to provide to skip to a particular spot in the list
#' #' @param pageSize Number of results to return in the list
#' #' @param filter The raw filter text to constrain the results
#' #' @importFrom googleAuthR gar_api_generator
#' #' @export
#' projects.builds.list <- function(projectId, pageToken = NULL, pageSize = NULL, filter = NULL) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/builds", projectId)
#'     # cloudbuild.projects.builds.list
#'     pars = list(pageToken = pageToken, pageSize = pageSize, filter = filter)
#'     f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
#'         data_parse_function = function(x) x)
#'     f()
#'
#' }
#'
#' #' Returns information about a `BuildTrigger`.This API is experimental.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param projectId ID of the project that owns the trigger
#' #' @param triggerId ID of the `BuildTrigger` to get
#' #' @importFrom googleAuthR gar_api_generator
#' #' @export
#' projects.triggers.get <- function(projectId, triggerId) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s",
#'         projectId, triggerId)
#'     # cloudbuild.projects.triggers.get
#'     f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
#'     f()
#'
#' }
#'
#' #' Updates a `BuildTrigger` by its project ID and trigger ID.This API is experimental.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param BuildTrigger The \link{BuildTrigger} object to pass to this method
#' #' @param projectId ID of the project that owns the trigger
#' #' @param triggerId ID of the `BuildTrigger` to update
#' #' @importFrom googleAuthR gar_api_generator
#' #' @family BuildTrigger functions
#' #' @export
#' projects.triggers.patch <- function(BuildTrigger, projectId, triggerId) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s",
#'         projectId, triggerId)
#'     # cloudbuild.projects.triggers.patch
#'     f <- googleAuthR::gar_api_generator(url, "PATCH", data_parse_function = function(x) x)
#'     stopifnot(inherits(BuildTrigger, "gar_BuildTrigger"))
#'
#'     f(the_body = BuildTrigger)
#'
#' }
#'
#' #' Deletes a `BuildTrigger` by its project ID and trigger ID.This API is experimental.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param projectId ID of the project that owns the trigger
#' #' @param triggerId ID of the `BuildTrigger` to delete
#' #' @importFrom googleAuthR gar_api_generator
#' #' @export
#' projects.triggers.delete <- function(projectId, triggerId) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s",
#'         projectId, triggerId)
#'     # cloudbuild.projects.triggers.delete
#'     f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
#'     f()
#'
#' }
#'
#' #' Lists existing `BuildTrigger`s.This API is experimental.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param projectId ID of the project for which to list BuildTriggers
#' #' @param pageToken Token to provide to skip to a particular spot in the list
#' #' @param pageSize Number of results to return in the list
#' #' @importFrom googleAuthR gar_api_generator
#' #' @export
#' projects.triggers.list <- function(projectId, pageToken = NULL, pageSize = NULL) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers", projectId)
#'     # cloudbuild.projects.triggers.list
#'     pars = list(pageToken = pageToken, pageSize = pageSize)
#'     f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
#'         data_parse_function = function(x) x)
#'     f()
#'
#' }
#'
#' #' Creates a new `BuildTrigger`.This API is experimental.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param BuildTrigger The \link{BuildTrigger} object to pass to this method
#' #' @param projectId ID of the project for which to configure automatic builds
#' #' @importFrom googleAuthR gar_api_generator
#' #' @family BuildTrigger functions
#' #' @export
#' projects.triggers.create <- function(BuildTrigger, projectId) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers", projectId)
#'     # cloudbuild.projects.triggers.create
#'     f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
#'     stopifnot(inherits(BuildTrigger, "gar_BuildTrigger"))
#'
#'     f(the_body = BuildTrigger)
#'
#' }
#'
#' #' Runs a `BuildTrigger` at a particular source revision.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param RepoSource The \link{RepoSource} object to pass to this method
#' #' @param projectId ID of the project
#' #' @param triggerId ID of the trigger
#' #' @importFrom googleAuthR gar_api_generator
#' #' @family RepoSource functions
#' #' @export
#' projects.triggers.run <- function(RepoSource, projectId, triggerId) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/projects/%s/triggers/%s:run",
#'         projectId, triggerId)
#'     # cloudbuild.projects.triggers.run
#'     f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
#'     stopifnot(inherits(RepoSource, "gar_RepoSource"))
#'
#'     f(the_body = RepoSource)
#'
#' }
#'
#' #' Starts asynchronous cancellation on a long-running operation.  The servermakes a best effort to cancel the operation, but success is notguaranteed.  If the server doesn't support this method, it returns`google.rpc.Code.UNIMPLEMENTED`.  Clients can useOperations.GetOperation orother methods to check whether the cancellation succeeded or whether theoperation completed despite cancellation. On successful cancellation,the operation is not deleted; instead, it becomes an operation withan Operation.error value with a google.rpc.Status.code of 1,corresponding to `Code.CANCELLED`.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param CancelOperationRequest The \link{CancelOperationRequest} object to pass to this method
#' #' @param name The name of the operation resource to be cancelled
#' #' @importFrom googleAuthR gar_api_generator
#' #' @family CancelOperationRequest functions
#' #' @export
#' operations.cancel <- function(CancelOperationRequest, name) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/{+name}:cancel", name)
#'     # cloudbuild.operations.cancel
#'     f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
#'     stopifnot(inherits(CancelOperationRequest, "gar_CancelOperationRequest"))
#'
#'     f(the_body = CancelOperationRequest)
#'
#' }
#'
#' #' Lists operations that match the specified filter in the request. If theserver doesn't support this method, it returns `UNIMPLEMENTED`.NOTE: the `name` binding allows API services to override the bindingto use different resource name schemes, such as `users/*/operations`. Tooverride the binding, API services can add a binding such as`'/v1/{name=users/*}/operations'` to their service configuration.For backwards compatibility, the default name includes the operationscollection id, however overriding users must ensure the name bindingis the parent resource, without the operations collection id.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param name The name of the operation's parent resource
#' #' @param filter The standard list filter
#' #' @param pageToken The standard list page token
#' #' @param pageSize The standard list page size
#' #' @importFrom googleAuthR gar_api_generator
#' #' @export
#' operations.list <- function(name, filter = NULL, pageToken = NULL, pageSize = NULL) {
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/{+name}", name)
#'     # cloudbuild.operations.list
#'     pars = list(filter = filter, pageToken = pageToken, pageSize = pageSize)
#'     f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
#'         data_parse_function = function(x) x)
#'     f()
#'
#' }
#'
#'
#' #' Gets the latest state of a long-running operation.  Clients can use thismethod to poll the operation result at intervals as recommended by the APIservice.
#' #'
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' #'
#' #' @seealso \href{https://cloud.google.com/cloud-build/docs/}{Google Documentation}
#' #'
#' #' @details
#' #' Authentication scopes used by this function are:
#' #' \itemize{
#' #'   \item https://www.googleapis.com/auth/cloud-platform
#' #' }
#' #'
#' #' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' #' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' #' See \code{\link[googleAuthR]{gar_auth}} for details.
#' #'
#' #' @param name The name of the operation resource
#' #' @importFrom googleAuthR gar_api_generator
#' #' @export
#'
#'
#' operations.get <- function(name) {
#'
#'
#'     url <- sprintf("https://cloudbuild.googleapis.com/v1/{+name}", name)
#'     # cloudbuild.operations.get
#'
#'     f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
#'
#'     f()
#'
#'
#' }
#'
#'
#'
