#' Cloud Scheduler API
#' Creates and manages jobs run on a regular recurring schedule.
#'
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2019-11-04 15:44:16
#' filename: R/funcs_schedule.R
#' api_json: schedule
#'
#' @details
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' @docType package
#' @name cloudscheduler_googleAuthR
#'
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x))
        rmNullObs(x) else x)
}

#' Lists information about the supported locations for this service.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The resource that owns the locations collection, if applicable
#' @param pageToken The standard list page token
#' @param pageSize The standard list page size
#' @param filter The standard list filter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.list <- function(name, pageToken = NULL, pageSize = NULL, filter = NULL) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}/locations",
        name)
    # cloudscheduler.projects.locations.list
    pars = list(pageToken = pageToken, pageSize = pageSize, filter = filter)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Gets information about a location.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name Resource name for the location
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.get <- function(name) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}", name)
    # cloudscheduler.projects.locations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Gets a job.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.jobs.get <- function(name) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}", name)
    # cloudscheduler.projects.locations.jobs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Updates a job.If successful, the updated Job is returned. If the job doesnot exist, `NOT_FOUND` is returned.If UpdateJob does not successfully return, it is possible for thejob to be in an Job.State.UPDATE_FAILED state. A job in this state maynot be executed. If this happens, retry the UpdateJob requestuntil a successful response is received.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Job The \link{Job} object to pass to this method
#' @param name Optionally caller-specified in CreateJob, after
#' @param updateMask A  mask used to specify which fields of the job are being updated
#' @importFrom googleAuthR gar_api_generator
#' @family Job functions
#' @export
projects.locations.jobs.patch <- function(Job, name, updateMask = NULL) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}", name)
    # cloudscheduler.projects.locations.jobs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(Job, "gar_Job"))

    f(the_body = Job)

}

#' Pauses a job.If a job is paused then the system will stop executing the jobuntil it is re-enabled via ResumeJob. Thestate of the job is stored in state; if paused itwill be set to Job.State.PAUSED. A job must be in Job.State.ENABLEDto be paused.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param PauseJobRequest The \link{PauseJobRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family PauseJobRequest functions
#' @export
projects.locations.jobs.pause <- function(PauseJobRequest, name) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}:pause", name)
    # cloudscheduler.projects.locations.jobs.pause
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PauseJobRequest, "gar_PauseJobRequest"))

    f(the_body = PauseJobRequest)

}

#' Deletes a job.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.jobs.delete <- function(name) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}", name)
    # cloudscheduler.projects.locations.jobs.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Lists jobs.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent Required
#' @param pageToken A token identifying a page of results the server will return
#' @param pageSize Requested page size
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.jobs.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+parent}/jobs", parent)
    # cloudscheduler.projects.locations.jobs.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Creates a job.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Job The \link{Job} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family Job functions
#' @export
projects.locations.jobs.create <- function(Job, parent) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+parent}/jobs", parent)
    # cloudscheduler.projects.locations.jobs.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Job, "gar_Job"))

    f(the_body = Job)

}

#' Forces a job to run now.When this method is called, Cloud Scheduler will dispatch the job, evenif the job is already running.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param RunJobRequest The \link{RunJobRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family RunJobRequest functions
#' @export
projects.locations.jobs.run <- function(RunJobRequest, name) {
    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}:run", name)
    # cloudscheduler.projects.locations.jobs.run
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(RunJobRequest, "gar_RunJobRequest"))

    f(the_body = RunJobRequest)

}


#' Resume a job.This method reenables a job after it has been Job.State.PAUSED. Thestate of a job is stored in Job.state; after calling this method itwill be set to Job.State.ENABLED. A job must be inJob.State.PAUSED to be resumed.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/scheduler/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param ResumeJobRequest The \link{ResumeJobRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ResumeJobRequest functions
#' @export
projects.locations.jobs.resume <- function(ResumeJobRequest, name) {


    url <- sprintf("https://cloudscheduler.googleapis.com/v1/{+name}:resume", name)
    # cloudscheduler.projects.locations.jobs.resume

    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)

    stopifnot(inherits(ResumeJobRequest, "gar_ResumeJobRequest"))

    f(the_body = ResumeJobRequest)


}



