#' #' Cloud Build API Objects
#' #' Creates and manages builds on Google Cloud Platform.
#' #'
#' #' Auto-generated code by googleAuthR::gar_create_api_objects
#' #'  at 2019-11-03 21:20:58
#' #' filename: R/objects_build.R
#' #' api_json: build
#' #'
#' #' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton
#'
#' #' PullRequestFilter Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' PullRequestFilter contains filter properties for matching GitHub PullRequests.
#' #'
#' #' @param commentControl Whether to block builds on a '/gcbrun' comment from a repository owner or
#' #' @param branch Regex of branches to match
#' #'
#' #' @return PullRequestFilter object
#' #'
#' #' @family PullRequestFilter functions
#' #' @export
#' PullRequestFilter <- function(commentControl = NULL, branch = NULL) {
#'     structure(list(commentControl = commentControl, branch = branch), class = "gar_PullRequestFilter")
#' }
#'
#' #' ListBuildTriggersResponse Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Response containing existing `BuildTriggers`.
#' #'
#' #' @param triggers `BuildTriggers` for the project, sorted by `create_time` descending
#' #' @param nextPageToken Token to receive the next page of results
#' #'
#' #' @return ListBuildTriggersResponse object
#' #'
#' #' @family ListBuildTriggersResponse functions
#' #' @export
#' ListBuildTriggersResponse <- function(triggers = NULL, nextPageToken = NULL) {
#'     structure(list(triggers = triggers, nextPageToken = nextPageToken), class = "gar_ListBuildTriggersResponse")
#' }
#'
#' #' BuiltImage Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' An image built by the pipeline.
#' #'
#' #' @param name Name used to push the container image to Google Container Registry, as
#' #' @param digest Docker Registry 2
#' #' @param pushTiming Output only
#' #'
#' #' @return BuiltImage object
#' #'
#' #' @family BuiltImage functions
#' #' @export
#' BuiltImage <- function(name = NULL, digest = NULL, pushTiming = NULL) {
#'     structure(list(name = name, digest = digest, pushTiming = pushTiming), class = "gar_BuiltImage")
#' }
#'
#' #' Hash Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Container message for hash values.
#' #'
#' #' @param type The type of hash that was performed
#' #' @param value The hash value
#' #'
#' #' @return Hash object
#' #'
#' #' @family Hash functions
#' #' @export
#' Hash <- function(type = NULL, value = NULL) {
#'     structure(list(type = type, value = value), class = "gar_Hash")
#' }
#'
#' #' Secret Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Pairs a set of secret environment variables containing encryptedvalues with the Cloud KMS key to use to decrypt the value.
#' #'
#' #' @param Secret.secretEnv The \link{Secret.secretEnv} object or list of objects
#' #' @param kmsKeyName Cloud KMS key name to use to decrypt these envs
#' #' @param secretEnv Map of environment variable name to its encrypted value
#' #'
#' #' @return Secret object
#' #'
#' #' @family Secret functions
#' #' @export
#' Secret <- function(Secret.secretEnv = NULL, kmsKeyName = NULL, secretEnv = NULL) {
#'     structure(list(Secret.secretEnv = Secret.secretEnv, kmsKeyName = kmsKeyName,
#'         secretEnv = secretEnv), class = "gar_Secret")
#' }
#'
#' #' Secret.secretEnv Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Map of environment variable name to its encrypted value.Secret environment variables must be unique across all of a build'ssecrets, and must be used by at least one build step. Values can be at most64 KB in size. There can be at most 100 secret values across all of abuild's secrets.
#' #'
#' #'
#' #'
#' #' @return Secret.secretEnv object
#' #'
#' #' @family Secret functions
#' #' @export
#' Secret.secretEnv <- function() {
#'     list()
#' }
#'
#' #' Empty Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' A generic empty message that you can re-use to avoid defining duplicatedempty messages in your APIs. A typical example is to use it as the requestor the response type of an API method. For instance:    service Foo {      rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);    }The JSON representation for `Empty` is empty JSON object `{}`.
#' #'
#' #'
#' #'
#' #' @return Empty object
#' #'
#' #' @family Empty functions
#' #' @export
#' Empty <- function() {
#'     list()
#' }
#'
#' #' PushFilter Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Push contains filter properties for matching GitHub git pushes.
#' #'
#' #' @param branch Regexes matching branches to build
#' #' @param tag Regexes matching tags to build
#' #'
#' #' @return PushFilter object
#' #'
#' #' @family PushFilter functions
#' #' @export
#' PushFilter <- function(branch = NULL, tag = NULL) {
#'     structure(list(branch = branch, tag = tag), class = "gar_PushFilter")
#' }
#'
#'
#'
#' #' RetryBuildRequest Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Specifies a build to retry.
#' #'
#' #'
#' #'
#' #' @return RetryBuildRequest object
#' #'
#' #' @family RetryBuildRequest functions
#' #' @export
#' RetryBuildRequest <- function() {
#'     list()
#' }
#'
#' #' ArtifactResult Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' An artifact that was uploaded during a build. Thisis a single record in the artifact manifest JSON file.
#' #'
#' #' @param fileHash The file hash of the artifact
#' #' @param location The path of an artifact in a Google Cloud Storage bucket, with the
#' #'
#' #' @return ArtifactResult object
#' #'
#' #' @family ArtifactResult functions
#' #' @export
#' ArtifactResult <- function(fileHash = NULL, location = NULL) {
#'     structure(list(fileHash = fileHash, location = location), class = "gar_ArtifactResult")
#' }
#'
#' #' GitHubEventsConfig Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' GitHubEventsConfig describes the configuration of a trigger that creates abuild whenever a GitHub event is received.This message is experimental.
#' #'
#' #' @param pullRequest filter to match changes in pull requests
#' #' @param push filter to match changes in refs like branches, tags
#' #' @param installationId The installationID that emits the GitHub event
#' #' @param owner Owner of the repository
#' #' @param name Name of the repository
#' #'
#' #' @return GitHubEventsConfig object
#' #'
#' #' @family GitHubEventsConfig functions
#' #' @export
#' GitHubEventsConfig <- function(pullRequest = NULL, push = NULL, installationId = NULL,
#'     owner = NULL, name = NULL) {
#'     structure(list(pullRequest = pullRequest, push = push, installationId = installationId,
#'         owner = owner, name = name), class = "gar_GitHubEventsConfig")
#' }
#'
#' #' Artifacts Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Artifacts produced by a build that should be uploaded uponsuccessful completion of all build steps.
#' #'
#' #' @param images A list of images to be pushed upon the successful completion of all build
#' #' @param objects A list of objects to be uploaded to Cloud Storage upon successful
#' #'
#' #' @return Artifacts object
#' #'
#' #' @family Artifacts functions
#' #' @export
#' Artifacts <- function(images = NULL, objects = NULL) {
#'     structure(list(images = images, objects = objects), class = "gar_Artifacts")
#' }
#'
#' #' BuildOperationMetadata Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Metadata for build operations.
#' #'
#' #' @param build The build that the operation is tracking
#' #'
#' #' @return BuildOperationMetadata object
#' #'
#' #' @family BuildOperationMetadata functions
#' #' @export
#' BuildOperationMetadata <- function(build = NULL) {
#'     structure(list(build = build), class = "gar_BuildOperationMetadata")
#' }
#'
#' #' SourceProvenance Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Provenance of the source. Ways to find the original source, or verify thatsome source was used for this build.
#' #'
#' #' @param SourceProvenance.fileHashes The \link{SourceProvenance.fileHashes} object or list of objects
#' #' @param fileHashes Output only
#' #' @param resolvedRepoSource A copy of the build's `source
#' #' @param resolvedStorageSource A copy of the build's `source
#' #'
#' #' @return SourceProvenance object
#' #'
#' #' @family SourceProvenance functions
#' #' @export
#' SourceProvenance <- function(SourceProvenance.fileHashes = NULL, fileHashes = NULL,
#'     resolvedRepoSource = NULL, resolvedStorageSource = NULL) {
#'     structure(list(SourceProvenance.fileHashes = SourceProvenance.fileHashes, fileHashes = fileHashes,
#'         resolvedRepoSource = resolvedRepoSource, resolvedStorageSource = resolvedStorageSource),
#'         class = "gar_SourceProvenance")
#' }
#'
#' #' SourceProvenance.fileHashes Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Output only. Hash(es) of the build source, which can be used to verify thatthe original source integrity was maintained in the build. Note that`FileHashes` will only be populated if `BuildOptions` has requested a`SourceProvenanceHash`.The keys to this map are file paths used as build source and the valuescontain the hash values for those files.If the build source came in a single package such as a gzipped tarfile(`.tar.gz`), the `FileHash` will be for the single path to that file.
#' #'
#' #'
#' #'
#' #' @return SourceProvenance.fileHashes object
#' #'
#' #' @family SourceProvenance functions
#' #' @export
#' SourceProvenance.fileHashes <- function() {
#'     list()
#' }
#'
#' #' CancelOperationRequest Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' The request message for Operations.CancelOperation.
#' #'
#' #'
#' #'
#' #' @return CancelOperationRequest object
#' #'
#' #' @family CancelOperationRequest functions
#' #' @export
#' CancelOperationRequest <- function() {
#'     list()
#' }
#'
#' #' Operation Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' This resource represents a long-running operation that is the result of anetwork API call.
#' #'
#' #' @param Operation.metadata The \link{Operation.metadata} object or list of objects
#' #' @param Operation.response The \link{Operation.response} object or list of objects
#' #' @param name The server-assigned name, which is only unique within the same service that
#' #' @param error The error result of the operation in case of failure or cancellation
#' #' @param metadata Service-specific metadata associated with the operation
#' #' @param done If the value is `false`, it means the operation is still in progress
#' #' @param response The normal response of the operation in case of success
#' #'
#' #' @return Operation object
#' #'
#' #' @family Operation functions
#' #' @export
#' Operation <- function(Operation.metadata = NULL, Operation.response = NULL, name = NULL,
#'     error = NULL, metadata = NULL, done = NULL, response = NULL) {
#'     structure(list(Operation.metadata = Operation.metadata, Operation.response = Operation.response,
#'         name = name, error = error, metadata = metadata, done = done, response = response),
#'         class = "gar_Operation")
#' }
#'
#' #' Operation.metadata Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Service-specific metadata associated with the operation.  It typicallycontains progress information and common metadata such as create time.Some services might not provide such metadata.  Any method that returns along-running operation should document the metadata type, if any.
#' #'
#' #'
#' #'
#' #' @return Operation.metadata object
#' #'
#' #' @family Operation functions
#' #' @export
#' Operation.metadata <- function() {
#'     list()
#' }
#'
#' #' Operation.response Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' The normal response of the operation in case of success.  If the originalmethod returns no data on success, such as `Delete`, the response is`google.protobuf.Empty`.  If the original method is standard`Get`/`Create`/`Update`, the response should be the resource.  For othermethods, the response should have the type `XxxResponse`, where `Xxx`is the original method name.  For example, if the original method nameis `TakeSnapshot()`, the inferred response type is`TakeSnapshotResponse`.
#' #'
#' #'
#' #'
#' #' @return Operation.response object
#' #'
#' #' @family Operation functions
#' #' @export
#' Operation.response <- function() {
#'     list()
#' }
#'
#'
#' #' BuildStep Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' A step in the build pipeline.
#' #'
#' #' @param args A list of arguments that will be presented to the step when it is started
#' #' @param pullTiming Output only
#' #' @param timeout Time limit for executing this build step
#' #' @param status Output only
#' #' @param name Required
#' #' @param id Unique identifier for this build step, used in `wait_for` to
#' #' @param secretEnv A list of environment variables which are encrypted using a Cloud Key
#' #' @param dir Working directory to use when running this step's container
#' #' @param env A list of environment variable definitions to be used when running a step
#' #' @param waitFor The ID(s) of the step(s) that this build step depends on
#' #' @param timing Output only
#' #' @param entrypoint Entrypoint to be used instead of the build step image's default entrypoint
#' #' @param volumes List of volumes to mount into the build step
#' #'
#' #' @return BuildStep object
#' #'
#' #' @family BuildStep functions
#' #' @export
#' BuildStep <- function(args = NULL, pullTiming = NULL, timeout = NULL, status = NULL,
#'     name = NULL, id = NULL, secretEnv = NULL, dir = NULL, env = NULL, waitFor = NULL,
#'     timing = NULL, entrypoint = NULL, volumes = NULL) {
#'     structure(list(args = args, pullTiming = pullTiming, timeout = timeout, status = status,
#'         name = name, id = id, secretEnv = secretEnv, dir = dir, env = env, waitFor = waitFor,
#'         timing = timing, entrypoint = entrypoint, volumes = volumes), class = "gar_BuildStep")
#' }
#'
#' #' FileHashes Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Container message for hashes of byte content of files, used inSourceProvenance messages to verify integrity of source input to the build.
#' #'
#' #' @param fileHash Collection of file hashes
#' #'
#' #' @return FileHashes object
#' #'
#' #' @family FileHashes functions
#' #' @export
#' FileHashes <- function(fileHash = NULL) {
#'     structure(list(fileHash = fileHash), class = "gar_FileHashes")
#' }
#'
#' #' Status Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' The `Status` type defines a logical error model that is suitable fordifferent programming environments, including REST APIs and RPC APIs. It isused by [gRPC](https://github.com/grpc). Each `Status` message containsthree pieces of data: error code, error message, and error details.You can find out more about this error model and how to work with it in the[API Design Guide](https://cloud.google.com/apis/design/errors).
#' #'
#' #' @param code The status code, which should be an enum value of google
#' #' @param message A developer-facing error message, which should be in English
#' #' @param details A list of messages that carry the error details
#' #'
#' #' @return Status object
#' #'
#' #' @family Status functions
#' #' @export
#' Status <- function(code = NULL, message = NULL, details = NULL) {
#'     structure(list(code = code, message = message, details = details), class = "gar_Status")
#' }
#'
#' #' BuildTrigger Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Configuration for an automated build in response to source repositorychanges.
#' #'
#' #' @param BuildTrigger.substitutions The \link{BuildTrigger.substitutions} object or list of objects
#' #' @param filename Path, from the source root, to a file whose contents is used for the
#' #' @param name User assigned name of the trigger
#' #' @param id Output only
#' #' @param tags Tags for annotation of a `BuildTrigger`
#' #' @param build Contents of the build template
#' #' @param ignoredFiles ignored_files and included_files are file glob matches using
#' #' @param github GitHubEventsConfig describes the configuration of a trigger that creates
#' #' @param substitutions Substitutions data for Build resource
#' #' @param includedFiles If any of the files altered in the commit pass the ignored_files
#' #' @param disabled If true, the trigger will never result in a build
#' #' @param createTime Output only
#' #' @param triggerTemplate Template describing the types of source changes to trigger a build
#' #' @param description Human-readable description of this trigger
#' #'
#' #' @return BuildTrigger object
#' #'
#' #' @family BuildTrigger functions
#' #' @export
#' BuildTrigger <- function(BuildTrigger.substitutions = NULL, filename = NULL, name = NULL,
#'     id = NULL, tags = NULL, build = NULL, ignoredFiles = NULL, github = NULL, substitutions = NULL,
#'     includedFiles = NULL, disabled = NULL, createTime = NULL, triggerTemplate = NULL,
#'     description = NULL) {
#'     structure(list(BuildTrigger.substitutions = BuildTrigger.substitutions, filename = filename,
#'         name = name, id = id, tags = tags, build = build, ignoredFiles = ignoredFiles,
#'         github = github, substitutions = substitutions, includedFiles = includedFiles,
#'         disabled = disabled, createTime = createTime, triggerTemplate = triggerTemplate,
#'         description = description), class = "gar_BuildTrigger")
#' }
#'
#' #' BuildTrigger.substitutions Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Substitutions data for Build resource.
#' #'
#' #'
#' #'
#' #' @return BuildTrigger.substitutions object
#' #'
#' #' @family BuildTrigger functions
#' #' @export
#' BuildTrigger.substitutions <- function() {
#'     list()
#' }
#'
#' #' Build.substitutions Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Substitutions data for `Build` resource.
#' #'
#' #'
#' #'
#' #' @return Build.substitutions object
#' #'
#' #' @family Build functions
#' #' @export
#' Build.substitutions <- function() {
#'     list()
#' }
#'
#' #' Build.timing Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Output only. Stores timing information for phases of the build. Valid keysare:* BUILD: time to execute all build steps* PUSH: time to push all specified images.* FETCHSOURCE: time to fetch source.If the build does not specify source or images,these keys will not be included.
#' #'
#' #'
#' #'
#' #' @return Build.timing object
#' #'
#' #' @family Build functions
#' #' @export
#' Build.timing <- function() {
#'     list()
#' }
#'
#' #' CancelBuildRequest Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Request to cancel an ongoing build.
#' #'
#' #'
#' #'
#' #' @return CancelBuildRequest object
#' #'
#' #' @family CancelBuildRequest functions
#' #' @export
#' CancelBuildRequest <- function() {
#'     list()
#' }
#'
#' #' Volume Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Volume describes a Docker container volume which is mounted into build stepsin order to persist files across build step execution.
#' #'
#' #' @param path Path at which to mount the volume
#' #' @param name Name of the volume to mount
#' #'
#' #' @return Volume object
#' #'
#' #' @family Volume functions
#' #' @export
#' Volume <- function(path = NULL, name = NULL) {
#'     structure(list(path = path, name = name), class = "gar_Volume")
#' }
#'
#' #' ListBuildsResponse Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Response including listed builds.
#' #'
#' #' @param nextPageToken Token to receive the next page of results
#' #' @param builds Builds will be sorted by `create_time`, descending
#' #'
#' #' @return ListBuildsResponse object
#' #'
#' #' @family ListBuildsResponse functions
#' #' @export
#' ListBuildsResponse <- function(nextPageToken = NULL, builds = NULL) {
#'     structure(list(nextPageToken = nextPageToken, builds = builds), class = "gar_ListBuildsResponse")
#' }
#'
#' #' ListOperationsResponse Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' The response message for Operations.ListOperations.
#' #'
#' #' @param operations A list of operations that matches the specified filter in the request
#' #' @param nextPageToken The standard List next-page token
#' #'
#' #' @return ListOperationsResponse object
#' #'
#' #' @family ListOperationsResponse functions
#' #' @export
#' ListOperationsResponse <- function(operations = NULL, nextPageToken = NULL) {
#'     structure(list(operations = operations, nextPageToken = nextPageToken), class = "gar_ListOperationsResponse")
#' }
#'
#' #' TimeSpan Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Start and end times for a build execution phase.
#' #'
#' #' @param endTime End of time span
#' #' @param startTime Start of time span
#' #'
#' #' @return TimeSpan object
#' #'
#' #' @family TimeSpan functions
#' #' @export
#' TimeSpan <- function(endTime = NULL, startTime = NULL) {
#'     structure(list(endTime = endTime, startTime = startTime), class = "gar_TimeSpan")
#' }
#'
#' #' BuildOptions Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Optional arguments to enable specific features of builds.
#' #'
#' #' @param logStreamingOption Option to define build log streaming behavior to Google Cloud
#' #' @param workerPool Option to specify a `WorkerPool` for the build
#' #' @param env A list of global environment variable definitions that will exist for all
#' #' @param logging Option to specify the logging mode, which determines where the logs are
#' #' @param requestedVerifyOption Requested verifiability options
#' #' @param substitutionOption Option to specify behavior when there is an error in the substitution
#' #' @param diskSizeGb Requested disk size for the VM that runs the build
#' #' @param secretEnv A list of global environment variables, which are encrypted using a Cloud
#' #' @param sourceProvenanceHash Requested hash for SourceProvenance
#' #' @param machineType Compute Engine machine type on which to run the build
#' #' @param volumes Global list of volumes to mount for ALL build steps
#' #'
#' #' @return BuildOptions object
#' #'
#' #' @family BuildOptions functions
#' #' @export
#' BuildOptions <- function(logStreamingOption = NULL, workerPool = NULL, env = NULL,
#'     logging = NULL, requestedVerifyOption = NULL, substitutionOption = NULL, diskSizeGb = NULL,
#'     secretEnv = NULL, sourceProvenanceHash = NULL, machineType = NULL, volumes = NULL) {
#'     structure(list(logStreamingOption = logStreamingOption, workerPool = workerPool,
#'         env = env, logging = logging, requestedVerifyOption = requestedVerifyOption,
#'         substitutionOption = substitutionOption, diskSizeGb = diskSizeGb, secretEnv = secretEnv,
#'         sourceProvenanceHash = sourceProvenanceHash, machineType = machineType, volumes = volumes),
#'         class = "gar_BuildOptions")
#' }
#'
#'
#'
#' #' Results Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Artifacts created by the build pipeline.
#' #'
#' #' @param artifactManifest Path to the artifact manifest
#' #' @param buildStepImages List of build step digests, in the order corresponding to build step
#' #' @param artifactTiming Time to push all non-container artifacts
#' #' @param buildStepOutputs List of build step outputs, produced by builder images, in the order
#' #' @param images Container images that were built as a part of the build
#' #' @param numArtifacts Number of artifacts uploaded
#' #'
#' #' @return Results object
#' #'
#' #' @family Results functions
#' #' @export
#' Results <- function(artifactManifest = NULL, buildStepImages = NULL, artifactTiming = NULL,
#'     buildStepOutputs = NULL, images = NULL, numArtifacts = NULL) {
#'     structure(list(artifactManifest = artifactManifest, buildStepImages = buildStepImages,
#'         artifactTiming = artifactTiming, buildStepOutputs = buildStepOutputs, images = images,
#'         numArtifacts = numArtifacts), class = "gar_Results")
#' }
#'
#'
#' #' ArtifactObjects Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Files in the workspace to upload to Cloud Storage upon successfulcompletion of all build steps.
#' #'
#' #' @param location Cloud Storage bucket and optional object path, in the form
#' #' @param paths Path globs used to match files in the build's workspace
#' #' @param timing Output only
#' #'
#' #' @return ArtifactObjects object
#' #'
#' #' @family ArtifactObjects functions
#' #' @export
#'
#'
#' ArtifactObjects <- function(location = NULL, paths = NULL, timing = NULL) {
#'
#'
#'
#'     structure(list(location = location, paths = paths, timing = timing), class = "gar_ArtifactObjects")
#' }
#'
