#' Cloud Run API Objects 
#' Deploy and manage user provided container images that scale automatically based on HTTP traffic.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2019-11-03 11:18:30
#' filename: R/objects.R
#' api_json: cr
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' Probe Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedProbe describes a health check to be performed against a container todetermine whether it is alive or ready to receive traffic.
#' 
#' @param periodSeconds (Optional)
#' @param failureThreshold (Optional)
#' @param initialDelaySeconds (Optional)
#' @param timeoutSeconds (Optional)
#' @param handler Cloud Run fully managed: not supported
#' @param successThreshold (Optional)
#' 
#' @return Probe object
#' 
#' @family Probe functions
#' @export
Probe <- function(periodSeconds = NULL, failureThreshold = NULL, initialDelaySeconds = NULL, 
    timeoutSeconds = NULL, handler = NULL, successThreshold = NULL) {
    structure(list(periodSeconds = periodSeconds, failureThreshold = failureThreshold, 
        initialDelaySeconds = initialDelaySeconds, timeoutSeconds = timeoutSeconds, 
        handler = handler, successThreshold = successThreshold), class = "gar_Probe")
}

#' ListDomainMappingsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ListDomainMappingsResponse is a list of DomainMapping resources.
#' 
#' @param unreachable Locations that could not be reached
#' @param metadata Metadata associated with this DomainMapping list
#' @param items List of DomainMappings
#' @param apiVersion The API version for this call such as 'domains
#' 
#' @return ListDomainMappingsResponse object
#' 
#' @family ListDomainMappingsResponse functions
#' @export
ListDomainMappingsResponse <- function(unreachable = NULL, metadata = NULL, items = NULL, 
    apiVersion = NULL) {
    structure(list(kind = kind, unreachable = unreachable, metadata = metadata, items = items, 
        apiVersion = apiVersion), class = "gar_ListDomainMappingsResponse")
}

#' RevisionStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' RevisionStatus communicates the observed state of the Revision (from thecontroller).
#' 
#' @param conditions Conditions communicates information about ongoing/complete
#' @param observedGeneration ObservedGeneration is the 'Generation' of the Revision that
#' @param imageDigest ImageDigest holds the resolved digest for the image specified
#' @param logUrl Specifies the generated logging url for this particular revision
#' @param serviceName Not currently used by Cloud Run
#' 
#' @return RevisionStatus object
#' 
#' @family RevisionStatus functions
#' @export
RevisionStatus <- function(conditions = NULL, observedGeneration = NULL, imageDigest = NULL, 
    logUrl = NULL, serviceName = NULL) {
    structure(list(conditions = conditions, observedGeneration = observedGeneration, 
        imageDigest = imageDigest, logUrl = logUrl, serviceName = serviceName), class = "gar_RevisionStatus")
}

#' ListAuthorizedDomainsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A list of Authorized Domains.
#' 
#' @param nextPageToken Continuation token for fetching the next page of results
#' @param domains The authorized domains belonging to the user
#' 
#' @return ListAuthorizedDomainsResponse object
#' 
#' @family ListAuthorizedDomainsResponse functions
#' @export
ListAuthorizedDomainsResponse <- function(nextPageToken = NULL, domains = NULL) {
    structure(list(nextPageToken = nextPageToken, domains = domains), class = "gar_ListAuthorizedDomainsResponse")
}

#' DomainMapping Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Resource to hold the state and status of a user's domain mapping.
#' 
#' @param status The current status of the DomainMapping
#' @param apiVersion The API version for this call such as 'domains
#' @param spec The spec for this DomainMapping
#' @param metadata Metadata associated with this BuildTemplate
#' 
#' @return DomainMapping object
#' 
#' @family DomainMapping functions
#' @export
DomainMapping <- function(status = NULL, apiVersion = NULL, spec = NULL, metadata = NULL) {
    structure(list(status = status, apiVersion = apiVersion, spec = spec, kind = kind, 
        metadata = metadata), class = "gar_DomainMapping")
}

#' RouteStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' RouteStatus communicates the observed state of the Route (from thecontroller).
#' 
#' @param url URL holds the url that will distribute traffic over the provided traffic
#' @param traffic Traffic holds the configured traffic distribution
#' @param conditions Conditions communicates information about ongoing/complete
#' @param observedGeneration ObservedGeneration is the 'Generation' of the Route that
#' @param address Similar to url, information on where the service is available on HTTP
#' 
#' @return RouteStatus object
#' 
#' @family RouteStatus functions
#' @export
RouteStatus <- function(url = NULL, traffic = NULL, conditions = NULL, observedGeneration = NULL, 
    address = NULL) {
    structure(list(url = url, traffic = traffic, conditions = conditions, observedGeneration = observedGeneration, 
        address = address), class = "gar_RouteStatus")
}

#' RevisionTemplate Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' RevisionTemplateSpec describes the data a revision should have when createdfrom a template. Based on:https://github.com/kubernetes/api/blob/e771f807/core/v1/types.go#L3179-L3190
#' 
#' @param metadata Optional metadata for this Revision, including labels and annotations
#' @param spec RevisionSpec holds the desired state of the Revision (from the client)
#' 
#' @return RevisionTemplate object
#' 
#' @family RevisionTemplate functions
#' @export
RevisionTemplate <- function(metadata = NULL, spec = NULL) {
    structure(list(metadata = metadata, spec = spec), class = "gar_RevisionTemplate")
}

#' DomainMappingStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The current state of the Domain Mapping.
#' 
#' @param mappedRouteName The name of the route that the mapping currently points to
#' @param conditions Array of observed DomainMappingConditions, indicating the current state
#' @param observedGeneration ObservedGeneration is the 'Generation' of the DomainMapping that
#' @param resourceRecords The resource records required to configure this domain mapping
#' 
#' @return DomainMappingStatus object
#' 
#' @family DomainMappingStatus functions
#' @export
DomainMappingStatus <- function(mappedRouteName = NULL, conditions = NULL, observedGeneration = NULL, 
    resourceRecords = NULL) {
    structure(list(mappedRouteName = mappedRouteName, conditions = conditions, observedGeneration = observedGeneration, 
        resourceRecords = resourceRecords), class = "gar_DomainMappingStatus")
}

#' ResourceRecord Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A DNS resource record.
#' 
#' @param name Relative name of the object affected by this record
#' @param type Resource record type
#' @param rrdata Data for this record
#' 
#' @return ResourceRecord object
#' 
#' @family ResourceRecord functions
#' @export
ResourceRecord <- function(name = NULL, type = NULL, rrdata = NULL) {
    structure(list(name = name, type = type, rrdata = rrdata), class = "gar_ResourceRecord")
}

#' AutoDomainMapping Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Resource to hold the state and status of a user's auto domain mapping.
#' 
#' @param metadata Metadata associated with this BuildTemplate
#' @param status The current status of the AutoDomainMapping
#' @param apiVersion The API version for this call such as 'serving
#' @param spec The spec for this AutoDomainMapping
#' 
#' @return AutoDomainMapping object
#' 
#' @family AutoDomainMapping functions
#' @export
AutoDomainMapping <- function(metadata = NULL, status = NULL, apiVersion = NULL, 
    spec = NULL) {
    structure(list(metadata = metadata, status = status, apiVersion = apiVersion, 
        spec = spec, kind = kind), class = "gar_AutoDomainMapping")
}

#' AuditLogConfig Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Provides the configuration for logging a type of permissions.Example:    {      'audit_log_configs': [        {          'log_type': 'DATA_READ',          'exempted_members': [            'user:jose@example.com'          ]        },        {          'log_type': 'DATA_WRITE',        }      ]    }This enables 'DATA_READ' and 'DATA_WRITE' logging, while exemptingjose@example.com from DATA_READ logging.
#' 
#' @param exemptedMembers Specifies the identities that do not cause logging for this type of
#' @param logType The log type that this config enables
#' 
#' @return AuditLogConfig object
#' 
#' @family AuditLogConfig functions
#' @export
AuditLogConfig <- function(exemptedMembers = NULL, logType = NULL) {
    structure(list(exemptedMembers = exemptedMembers, logType = logType), class = "gar_AuditLogConfig")
}

#' TrafficTarget Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' TrafficTarget holds a single entry of the routing table for a Route.
#' 
#' @param tag Tag is optionally used to expose a dedicated url for referencing
#' @param url Output only
#' @param configurationName ConfigurationName of a configuration to whose latest revision we will
#' @param percent Percent specifies percent of the traffic to this Revision or Configuration
#' @param revisionName RevisionName of a specific revision to which to send this portion of
#' @param latestRevision LatestRevision may be optionally provided to indicate that the latest
#' 
#' @return TrafficTarget object
#' 
#' @family TrafficTarget functions
#' @export
TrafficTarget <- function(tag = NULL, url = NULL, configurationName = NULL, percent = NULL, 
    revisionName = NULL, latestRevision = NULL) {
    structure(list(tag = tag, url = url, configurationName = configurationName, percent = percent, 
        revisionName = revisionName, latestRevision = latestRevision), class = "gar_TrafficTarget")
}

#' HTTPHeader Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedHTTPHeader describes a custom header to be used in HTTP probes
#' 
#' @param name Cloud Run fully managed: not supported
#' @param value Cloud Run fully managed: not supported
#' 
#' @return HTTPHeader object
#' 
#' @family HTTPHeader functions
#' @export
HTTPHeader <- function(name = NULL, value = NULL) {
    structure(list(name = name, value = value), class = "gar_HTTPHeader")
}

#' DomainMappingSpec Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The desired state of the Domain Mapping.
#' 
#' @param forceOverride If set, the mapping will override any mapping set before this spec was set
#' @param routeName The name of the Knative Route that this DomainMapping applies to
#' @param certificateMode The mode of the certificate
#' 
#' @return DomainMappingSpec object
#' 
#' @family DomainMappingSpec functions
#' @export
DomainMappingSpec <- function(forceOverride = NULL, routeName = NULL, certificateMode = NULL) {
    structure(list(forceOverride = forceOverride, routeName = routeName, certificateMode = certificateMode), 
        class = "gar_DomainMappingSpec")
}

#' SecurityContext Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedSecurityContext holds security configuration that will be applied to acontainer. Some fields are present in both SecurityContext andPodSecurityContext.  When both are set, the values in SecurityContext takeprecedence.
#' 
#' @param runAsUser (Optional)
#' 
#' @return SecurityContext object
#' 
#' @family SecurityContext functions
#' @export
SecurityContext <- function(runAsUser = NULL) {
    structure(list(runAsUser = runAsUser), class = "gar_SecurityContext")
}

#' ExecAction Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedExecAction describes a 'run in container' action.
#' 
#' @param command (Optional)
#' 
#' @return ExecAction object
#' 
#' @family ExecAction functions
#' @export
ExecAction <- function(command = NULL) {
    structure(list(command = command), class = "gar_ExecAction")
}

#' Policy Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Defines an Identity and Access Management (IAM) policy. It is used tospecify access control policies for Cloud Platform resources.A `Policy` is a collection of `bindings`. A `binding` binds one or more`members` to a single `role`. Members can be user accounts, service accounts,Google groups, and domains (such as G Suite). A `role` is a named list ofpermissions (defined by IAM or configured by users). A `binding` canoptionally specify a `condition`, which is a logic expression that furtherconstrains the role binding based on attributes about the request and/ortarget resource.**JSON Example**    {      'bindings': [        {          'role': 'roles/resourcemanager.organizationAdmin',          'members': [            'user:mike@example.com',            'group:admins@example.com',            'domain:google.com',            'serviceAccount:my-project-id@appspot.gserviceaccount.com'          ]        },        {          'role': 'roles/resourcemanager.organizationViewer',          'members': ['user:eve@example.com'],          'condition': {            'title': 'expirable access',            'description': 'Does not grant access after Sep 2020',            'expression': 'request.time <            timestamp('2020-10-01T00:00:00.000Z')',          }        }      ]    }**YAML Example**    bindings:    - members:      - user:mike@example.com      - group:admins@example.com      - domain:google.com      - serviceAccount:my-project-id@appspot.gserviceaccount.com      role: roles/resourcemanager.organizationAdmin    - members:      - user:eve@example.com      role: roles/resourcemanager.organizationViewer      condition:        title: expirable access        description: Does not grant access after Sep 2020        expression: request.time < timestamp('2020-10-01T00:00:00.000Z')For a description of IAM and its features, see the[IAM developer's guide](https://cloud.google.com/iam/docs).
#' 
#' @param etag `etag` is used for optimistic concurrency control as a way to help
#' @param version Specifies the format of the policy
#' @param auditConfigs Specifies cloud audit logging configuration for this policy
#' @param bindings Associates a list of `members` to a `role`
#' 
#' @return Policy object
#' 
#' @family Policy functions
#' @export
Policy <- function(etag = NULL, version = NULL, auditConfigs = NULL, bindings = NULL) {
    structure(list(etag = etag, version = version, auditConfigs = auditConfigs, bindings = bindings), 
        class = "gar_Policy")
}

#' ListLocationsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response message for Locations.ListLocations.
#' 
#' @param locations A list of locations that matches the specified filter in the request
#' @param nextPageToken The standard List next-page token
#' 
#' @return ListLocationsResponse object
#' 
#' @family ListLocationsResponse functions
#' @export
ListLocationsResponse <- function(locations = NULL, nextPageToken = NULL) {
    structure(list(locations = locations, nextPageToken = nextPageToken), class = "gar_ListLocationsResponse")
}

#' ConfigurationSpec Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ConfigurationSpec holds the desired state of the Configuration (from theclient).
#' 
#' @param template Optional metadata for this Revision, including labels and annotations
#' 
#' @return ConfigurationSpec object
#' 
#' @family ConfigurationSpec functions
#' @export
ConfigurationSpec <- function(template = NULL) {
    structure(list(template = template), class = "gar_ConfigurationSpec")
}

#' VolumeMount Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedVolumeMount describes a mounting of a Volume within a container.
#' 
#' @param name Cloud Run fully managed: not supported
#' @param readOnly (Optional)
#' @param mountPath Cloud Run fully managed: not supported
#' @param subPath (Optional)
#' 
#' @return VolumeMount object
#' 
#' @family VolumeMount functions
#' @export
VolumeMount <- function(name = NULL, readOnly = NULL, mountPath = NULL, subPath = NULL) {
    structure(list(name = name, readOnly = readOnly, mountPath = mountPath, subPath = subPath), 
        class = "gar_VolumeMount")
}

#' Revision Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Revision is an immutable snapshot of code and configuration.  A revisionreferences a container image. Revisions are created by updates to aConfiguration.See also:https://github.com/knative/serving/blob/master/docs/spec/overview.md#revision
#' 
#' @param status Status communicates the observed state of the Revision (from the
#' @param apiVersion The API version for this call such as 'serving
#' @param spec Spec holds the desired state of the Revision (from the client)
#' @param metadata Metadata associated with this Revision, including name, namespace, labels,
#' 
#' @return Revision object
#' 
#' @family Revision functions
#' @export
Revision <- function(status = NULL, apiVersion = NULL, spec = NULL, metadata = NULL) {
    structure(list(status = status, apiVersion = apiVersion, spec = spec, kind = kind, 
        metadata = metadata), class = "gar_Revision")
}

#' EnvVar Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' EnvVar represents an environment variable present in a Container.
#' 
#' @param value (Optional)
#' @param name Name of the environment variable
#' @param valueFrom (Optional)
#' 
#' @return EnvVar object
#' 
#' @family EnvVar functions
#' @export
EnvVar <- function(value = NULL, name = NULL, valueFrom = NULL) {
    structure(list(value = value, name = name, valueFrom = valueFrom), class = "gar_EnvVar")
}

#' RevisionSpec Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' RevisionSpec holds the desired state of the Revision (from the client).
#' 
#' @param timeoutSeconds TimeoutSeconds holds the max duration the instance is allowed for
#' @param serviceAccountName Email address of the IAM service account associated with the revision
#' @param containers Containers holds the single container that defines the unit of execution
#' @param volumes No description
#' @param containerConcurrency (Optional)
#' 
#' @return RevisionSpec object
#' 
#' @family RevisionSpec functions
#' @export
RevisionSpec <- function(timeoutSeconds = NULL, serviceAccountName = NULL, containers = NULL, 
    volumes = NULL, containerConcurrency = NULL) {
    structure(list(timeoutSeconds = timeoutSeconds, serviceAccountName = serviceAccountName, 
        containers = containers, volumes = volumes, containerConcurrency = containerConcurrency), 
        class = "gar_RevisionSpec")
}

#' ListRevisionsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ListRevisionsResponse is a list of Revision resources.
#' 
#' @param unreachable Locations that could not be reached
#' @param metadata Metadata associated with this revision list
#' @param items List of Revisions
#' @param apiVersion The API version for this call such as 'serving
#' 
#' @return ListRevisionsResponse object
#' 
#' @family ListRevisionsResponse functions
#' @export
ListRevisionsResponse <- function(unreachable = NULL, metadata = NULL, items = NULL, 
    apiVersion = NULL) {
    structure(list(kind = kind, unreachable = unreachable, metadata = metadata, items = items, 
        apiVersion = apiVersion), class = "gar_ListRevisionsResponse")
}

#' Status Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Status is a return value for calls that don't return other objects
#' 
#' @param code Suggested HTTP return code for this status, 0 if not set
#' @param message A human-readable description of the status of this operation
#' @param status Status of the operation
#' @param details Extended data associated with the reason
#' @param reason A machine-readable description of why this operation is in the
#' @param metadata Standard list metadata
#' 
#' @return Status object
#' 
#' @family Status functions
#' @export
Status <- function(code = NULL, message = NULL, status = NULL, details = NULL, reason = NULL, 
    metadata = NULL) {
    structure(list(code = code, message = message, status = status, details = details, 
        reason = reason, metadata = metadata), class = "gar_Status")
}

#' Binding Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Associates `members` with a `role`.
#' 
#' @param condition The condition that is associated with this binding
#' @param members Specifies the identities requesting access for a Cloud Platform resource
#' @param role Role that is assigned to `members`
#' 
#' @return Binding object
#' 
#' @family Binding functions
#' @export
Binding <- function(condition = NULL, members = NULL, role = NULL) {
    structure(list(condition = condition, members = members, role = role), class = "gar_Binding")
}

#' SecretKeySelector Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedSecretKeySelector selects a key of a Secret.
#' 
#' @param key Cloud Run fully managed: not supported
#' @param name Cloud Run fully managed: not supported
#' @param localObjectReference This field should not be used directly as it is meant to be inlined
#' @param optional (Optional)
#' 
#' @return SecretKeySelector object
#' 
#' @family SecretKeySelector functions
#' @export
SecretKeySelector <- function(key = NULL, name = NULL, localObjectReference = NULL, 
    optional = NULL) {
    structure(list(key = key, name = name, localObjectReference = localObjectReference, 
        optional = optional), class = "gar_SecretKeySelector")
}

#' ConfigurationStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ConfigurationStatus communicates the observed state of the Configuration(from the controller).
#' 
#' @param latestCreatedRevisionName LatestCreatedRevisionName is the last revision that was created from this
#' @param latestReadyRevisionName LatestReadyRevisionName holds the name of the latest Revision stamped out
#' @param conditions Conditions communicates information about ongoing/complete
#' @param observedGeneration ObservedGeneration is the 'Generation' of the Configuration that
#' 
#' @return ConfigurationStatus object
#' 
#' @family ConfigurationStatus functions
#' @export
ConfigurationStatus <- function(latestCreatedRevisionName = NULL, latestReadyRevisionName = NULL, 
    conditions = NULL, observedGeneration = NULL) {
    structure(list(latestCreatedRevisionName = latestCreatedRevisionName, latestReadyRevisionName = latestReadyRevisionName, 
        conditions = conditions, observedGeneration = observedGeneration), class = "gar_ConfigurationStatus")
}

#' ObjectMeta Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta is metadata that allpersisted resources must have, which includes all objects users must create.
#' 
#' @param ObjectMeta.labels The \link{ObjectMeta.labels} object or list of objects
#' @param ObjectMeta.annotations The \link{ObjectMeta.annotations} object or list of objects
#' @param creationTimestamp (Optional)
#' @param labels (Optional)
#' @param generation (Optional)
#' @param resourceVersion (Optional)
#' @param selfLink (Optional)
#' @param uid (Optional)
#' @param namespace Namespace defines the space within each name must be unique, within a
#' @param annotations (Optional)
#' @param generateName (Optional)
#' @param clusterName (Optional)
#' @param deletionGracePeriodSeconds (Optional)
#' @param name Name must be unique within a namespace, within a Cloud Run region
#' @param finalizers (Optional)
#' @param deletionTimestamp (Optional)
#' @param ownerReferences (Optional)
#' 
#' @return ObjectMeta object
#' 
#' @family ObjectMeta functions
#' @export
ObjectMeta <- function(ObjectMeta.labels = NULL, ObjectMeta.annotations = NULL, creationTimestamp = NULL, 
    labels = NULL, generation = NULL, resourceVersion = NULL, selfLink = NULL, uid = NULL, 
    namespace = NULL, annotations = NULL, generateName = NULL, clusterName = NULL, 
    deletionGracePeriodSeconds = NULL, name = NULL, finalizers = NULL, deletionTimestamp = NULL, 
    ownerReferences = NULL) {
    structure(list(ObjectMeta.labels = ObjectMeta.labels, ObjectMeta.annotations = ObjectMeta.annotations, 
        creationTimestamp = creationTimestamp, labels = labels, generation = generation, 
        resourceVersion = resourceVersion, selfLink = selfLink, uid = uid, namespace = namespace, 
        annotations = annotations, generateName = generateName, clusterName = clusterName, 
        deletionGracePeriodSeconds = deletionGracePeriodSeconds, name = name, finalizers = finalizers, 
        deletionTimestamp = deletionTimestamp, ownerReferences = ownerReferences), 
        class = "gar_ObjectMeta")
}

#' ObjectMeta.labels Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' (Optional)Map of string keys and values that can be used to organize and categorize(scope and select) objects. May match selectors of replication controllersand routes.More info: http://kubernetes.io/docs/user-guide/labels
#' 
#' 
#' 
#' @return ObjectMeta.labels object
#' 
#' @family ObjectMeta functions
#' @export
ObjectMeta.labels <- function() {
    list()
}

#' ObjectMeta.annotations Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' (Optional)Annotations is an unstructured key value map stored with a resource thatmay be set by external tools to store and retrieve arbitrary metadata. Theyare not queryable and should be preserved when modifying objects. Moreinfo: http://kubernetes.io/docs/user-guide/annotations
#' 
#' 
#' 
#' @return ObjectMeta.annotations object
#' 
#' @family ObjectMeta functions
#' @export
ObjectMeta.annotations <- function() {
    list()
}

#' ServiceSpec Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ServiceSpec holds the desired state of the Route (from the client), whichis used to manipulate the underlying Route and Configuration(s).
#' 
#' @param traffic Traffic specifies how to distribute traffic over a collection of Knative
#' @param template Template holds the latest specification for the Revision to
#' 
#' @return ServiceSpec object
#' 
#' @family ServiceSpec functions
#' @export
ServiceSpec <- function(traffic = NULL, template = NULL) {
    structure(list(traffic = traffic, template = template), class = "gar_ServiceSpec")
}

#' Service Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Service acts as a top-level container that manages a set of Routes andConfigurations which implement a network service. Service exists to provide asingular abstraction which can be access controlled, reasoned about, andwhich encapsulates software lifecycle decisions such as rollout policy andteam resource ownership. Service acts only as an orchestrator of theunderlying Routes and Configurations (much as a kubernetes Deploymentorchestrates ReplicaSets).The Service's controller will track the statuses of its owned Configurationand Route, reflecting their statuses and conditions as its own.See also:https://github.com/knative/serving/blob/master/docs/spec/overview.md#service
#' 
#' @param status Status communicates the observed state of the Service (from the
#' @param apiVersion The API version for this call such as 'serving
#' @param spec Spec holds the desired state of the Service (from the client)
#' @param metadata Metadata associated with this Service, including name, namespace, labels,
#' 
#' @return Service object
#' 
#' @family Service functions
#' @export
Service <- function(status = NULL, apiVersion = NULL, spec = NULL, metadata = NULL) {
    structure(list(status = status, apiVersion = apiVersion, spec = spec, kind = kind, 
        metadata = metadata), class = "gar_Service")
}

#' EnvVarSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedEnvVarSource represents a source for the value of an EnvVar.
#' 
#' @param configMapKeyRef (Optional)
#' @param secretKeyRef (Optional)
#' 
#' @return EnvVarSource object
#' 
#' @family EnvVarSource functions
#' @export
EnvVarSource <- function(configMapKeyRef = NULL, secretKeyRef = NULL) {
    structure(list(configMapKeyRef = configMapKeyRef, secretKeyRef = secretKeyRef), 
        class = "gar_EnvVarSource")
}

#' Handler Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedHandler defines a specific action that should be taken
#' 
#' @param tcpSocket (Optional)
#' @param exec (Optional)
#' @param httpGet (Optional)
#' 
#' @return Handler object
#' 
#' @family Handler functions
#' @export
Handler <- function(tcpSocket = NULL, exec = NULL, httpGet = NULL) {
    structure(list(tcpSocket = tcpSocket, exec = exec, httpGet = httpGet), class = "gar_Handler")
}

#' KeyToPath Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedMaps a string key to a path within a volume.
#' 
#' @param path Cloud Run fully managed: not supported
#' @param mode (Optional)
#' @param key Cloud Run fully managed: not supported
#' 
#' @return KeyToPath object
#' 
#' @family KeyToPath functions
#' @export
KeyToPath <- function(path = NULL, mode = NULL, key = NULL) {
    structure(list(path = path, mode = mode, key = key), class = "gar_KeyToPath")
}

#' Container Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A single application container.This specifies both the container to run, the command to run in the containerand the arguments to supply to it.Note that additional arguments may be supplied by the system to the containerat runtime.
#' 
#' @param volumeMounts (Optional)
#' @param ports (Optional)
#' @param args (Optional)
#' @param workingDir (Optional)
#' @param envFrom (Optional)
#' @param image Cloud Run fully managed: only supports containers from Google Container
#' @param name (Optional)
#' @param command No description
#' @param terminationMessagePolicy (Optional)
#' @param securityContext (Optional)
#' @param livenessProbe (Optional)
#' @param env (Optional)
#' @param imagePullPolicy (Optional)
#' @param readinessProbe (Optional)
#' @param resources (Optional)
#' @param terminationMessagePath (Optional)
#' 
#' @return Container object
#' 
#' @family Container functions
#' @export
Container <- function(volumeMounts = NULL, ports = NULL, args = NULL, workingDir = NULL, 
    envFrom = NULL, image = NULL, name = NULL, command = NULL, terminationMessagePolicy = NULL, 
    securityContext = NULL, livenessProbe = NULL, env = NULL, imagePullPolicy = NULL, 
    readinessProbe = NULL, resources = NULL, terminationMessagePath = NULL) {
    structure(list(volumeMounts = volumeMounts, ports = ports, args = args, workingDir = workingDir, 
        envFrom = envFrom, image = image, name = name, command = command, terminationMessagePolicy = terminationMessagePolicy, 
        securityContext = securityContext, livenessProbe = livenessProbe, env = env, 
        imagePullPolicy = imagePullPolicy, readinessProbe = readinessProbe, resources = resources, 
        terminationMessagePath = terminationMessagePath), class = "gar_Container")
}

#' TCPSocketAction Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedTCPSocketAction describes an action based on opening a socket
#' 
#' @param port Cloud Run fully managed: not supported
#' @param host (Optional)
#' 
#' @return TCPSocketAction object
#' 
#' @family TCPSocketAction functions
#' @export
TCPSocketAction <- function(port = NULL, host = NULL) {
    structure(list(port = port, host = host), class = "gar_TCPSocketAction")
}

#' AutoDomainMappingStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The current state of the Domain Mapping.
#' 
#' @param conditions Array of observed AutoDomainMappingConditions, indicating the current state
#' @param observedGeneration ObservedGeneration is the 'Generation' of the AutoDomainMapping that
#' @param resourceRecords The resource records required to configure this domain mapping
#' 
#' @return AutoDomainMappingStatus object
#' 
#' @family AutoDomainMappingStatus functions
#' @export
AutoDomainMappingStatus <- function(conditions = NULL, observedGeneration = NULL, 
    resourceRecords = NULL) {
    structure(list(conditions = conditions, observedGeneration = observedGeneration, 
        resourceRecords = resourceRecords), class = "gar_AutoDomainMappingStatus")
}

#' SecretEnvSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedSecretEnvSource selects a Secret to populate the environmentvariables with.The contents of the target Secret's Data field will represent thekey-value pairs as environment variables.
#' 
#' @param name Cloud Run fully managed: not supported
#' @param localObjectReference This field should not be used directly as it is meant to be inlined
#' @param optional (Optional)
#' 
#' @return SecretEnvSource object
#' 
#' @family SecretEnvSource functions
#' @export
SecretEnvSource <- function(name = NULL, localObjectReference = NULL, optional = NULL) {
    structure(list(name = name, localObjectReference = localObjectReference, optional = optional), 
        class = "gar_SecretEnvSource")
}

#' ResourceRequirements Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ResourceRequirements describes the compute resource requirements.
#' 
#' @param ResourceRequirements.limits The \link{ResourceRequirements.limits} object or list of objects
#' @param ResourceRequirements.requests The \link{ResourceRequirements.requests} object or list of objects
#' @param limits (Optional)
#' @param requests (Optional)
#' 
#' @return ResourceRequirements object
#' 
#' @family ResourceRequirements functions
#' @export
ResourceRequirements <- function(ResourceRequirements.limits = NULL, ResourceRequirements.requests = NULL, 
    limits = NULL, requests = NULL) {
    structure(list(ResourceRequirements.limits = ResourceRequirements.limits, ResourceRequirements.requests = ResourceRequirements.requests, 
        limits = limits, requests = requests), class = "gar_ResourceRequirements")
}

#' ResourceRequirements.limits Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' (Optional)Cloud Run fully managed: Only memory and CPU are supported. Note: The onlysupported value for CPU is '1'.Cloud Run for Anthos: supportedLimits describes the maximum amount of compute resources allowed.The values of the map is string form of the 'quantity' k8s type:https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go
#' 
#' 
#' 
#' @return ResourceRequirements.limits object
#' 
#' @family ResourceRequirements functions
#' @export
ResourceRequirements.limits <- function() {
    list()
}

#' ResourceRequirements.requests Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' (Optional)Cloud Run fully managed: Only memory and CPU are supported. Note: The onlysupported value for CPU is '1'.Cloud Run for Anthos: supportedRequests describes the minimum amount of compute resources required.If Requests is omitted for a container, it defaults to Limits if that isexplicitly specified, otherwise to an implementation-defined value.The values of the map is string form of the 'quantity' k8s type:https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go
#' 
#' 
#' 
#' @return ResourceRequirements.requests object
#' 
#' @family ResourceRequirements functions
#' @export
ResourceRequirements.requests <- function() {
    list()
}

#' SetIamPolicyRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request message for `SetIamPolicy` method.
#' 
#' @param policy REQUIRED: The complete policy to be applied to the `resource`
#' @param updateMask OPTIONAL: A FieldMask specifying which fields of the policy to modify
#' 
#' @return SetIamPolicyRequest object
#' 
#' @family SetIamPolicyRequest functions
#' @export
SetIamPolicyRequest <- function(policy = NULL, updateMask = NULL) {
    structure(list(policy = policy, updateMask = updateMask), class = "gar_SetIamPolicyRequest")
}

#' Configuration Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Configuration represents the 'floating HEAD' of a linear history ofRevisions, and optionally how the containers those revisions reference arebuilt. Users create new Revisions by updating the Configuration's spec. The'latest created' revision's name is available under status, as is the 'latestready' revision's name. See also:https://github.com/knative/serving/blob/master/docs/spec/overview.md#configuration
#' 
#' @param metadata Metadata associated with this Configuration, including name, namespace,
#' @param status Status communicates the observed state of the Configuration (from the
#' @param apiVersion The API version for this call such as 'serving
#' @param spec Spec holds the desired state of the Configuration (from the client)
#' 
#' @return Configuration object
#' 
#' @family Configuration functions
#' @export
Configuration <- function(metadata = NULL, status = NULL, apiVersion = NULL, spec = NULL) {
    structure(list(kind = kind, metadata = metadata, status = status, apiVersion = apiVersion, 
        spec = spec), class = "gar_Configuration")
}

#' ListRoutesResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ListRoutesResponse is a list of Route resources.
#' 
#' @param unreachable Locations that could not be reached
#' @param metadata Metadata associated with this Route list
#' @param items List of Routes
#' @param apiVersion The API version for this call such as 'serving
#' 
#' @return ListRoutesResponse object
#' 
#' @family ListRoutesResponse functions
#' @export
ListRoutesResponse <- function(unreachable = NULL, metadata = NULL, items = NULL, 
    apiVersion = NULL) {
    structure(list(kind = kind, unreachable = unreachable, metadata = metadata, items = items, 
        apiVersion = apiVersion), class = "gar_ListRoutesResponse")
}

#' Location Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A resource that represents Google Cloud Platform location.
#' 
#' @param Location.metadata The \link{Location.metadata} object or list of objects
#' @param Location.labels The \link{Location.labels} object or list of objects
#' @param metadata Service-specific metadata
#' @param labels Cross-service attributes for the location
#' @param name Resource name for the location, which may vary between implementations
#' @param locationId The canonical id for this location
#' @param displayName The friendly name for this location, typically a nearby city name
#' 
#' @return Location object
#' 
#' @family Location functions
#' @export
Location <- function(Location.metadata = NULL, Location.labels = NULL, metadata = NULL, 
    labels = NULL, name = NULL, locationId = NULL, displayName = NULL) {
    structure(list(Location.metadata = Location.metadata, Location.labels = Location.labels, 
        metadata = metadata, labels = labels, name = name, locationId = locationId, 
        displayName = displayName), class = "gar_Location")
}

#' Location.metadata Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Service-specific metadata. For example the available capacity at the givenlocation.
#' 
#' 
#' 
#' @return Location.metadata object
#' 
#' @family Location functions
#' @export
Location.metadata <- function() {
    list()
}

#' Location.labels Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cross-service attributes for the location. For example    {'cloud.googleapis.com/region': 'us-east1'}
#' 
#' 
#' 
#' @return Location.labels object
#' 
#' @family Location functions
#' @export
Location.labels <- function() {
    list()
}

#' GoogleCloudRunV1Condition Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Condition defines a generic condition for a Resource
#' 
#' @param status Status of the condition, one of True, False, Unknown
#' @param severity Optional
#' @param reason Optional
#' @param type type is used to communicate the status of the reconciliation process
#' @param message Optional
#' @param lastTransitionTime Optional
#' 
#' @return GoogleCloudRunV1Condition object
#' 
#' @family GoogleCloudRunV1Condition functions
#' @export
GoogleCloudRunV1Condition <- function(status = NULL, severity = NULL, reason = NULL, 
    type = NULL, message = NULL, lastTransitionTime = NULL) {
    structure(list(status = status, severity = severity, reason = reason, type = type, 
        message = message, lastTransitionTime = lastTransitionTime), class = "gar_GoogleCloudRunV1Condition")
}

#' ListMeta Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ListMeta describes metadata that synthetic resources must have, includinglists and various status objects. A resource may have only one of{ObjectMeta, ListMeta}.
#' 
#' @param continue continue may be set if the user set a limit on the number of items
#' @param selfLink SelfLink is a URL representing this object
#' @param resourceVersion String that identifies the server's internal version of this object that
#' 
#' @return ListMeta object
#' 
#' @family ListMeta functions
#' @export
ListMeta <- function(continue = NULL, selfLink = NULL, resourceVersion = NULL) {
    structure(list(continue = continue, selfLink = selfLink, resourceVersion = resourceVersion), 
        class = "gar_ListMeta")
}

#' SecretVolumeSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedThe contents of the target Secret's Data field will be presented in a volumeas files using the keys in the Data field as the file names.
#' 
#' @param defaultMode (Optional)
#' @param secretName Cloud Run fully managed: not supported
#' @param items (Optional)
#' @param optional (Optional)
#' 
#' @return SecretVolumeSource object
#' 
#' @family SecretVolumeSource functions
#' @export
SecretVolumeSource <- function(defaultMode = NULL, secretName = NULL, items = NULL, 
    optional = NULL) {
    structure(list(defaultMode = defaultMode, secretName = secretName, items = items, 
        optional = optional), class = "gar_SecretVolumeSource")
}

#' IntOrString Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' IntOrString is a type that can hold an int32 or a string.  When used inJSON or YAML marshalling and unmarshalling, it produces or consumes theinner type.  This allows you to have, for example, a JSON field that canaccept a name or number.
#' 
#' @param type The type of the value
#' @param intVal The int value
#' @param strVal The string value
#' 
#' @return IntOrString object
#' 
#' @family IntOrString functions
#' @export
IntOrString <- function(type = NULL, intVal = NULL, strVal = NULL) {
    structure(list(type = type, intVal = intVal, strVal = strVal), class = "gar_IntOrString")
}

#' LocalObjectReference Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedLocalObjectReference contains enough information to let you locate thereferenced object inside the same namespace.
#' 
#' @param name (Optional)
#' 
#' @return LocalObjectReference object
#' 
#' @family LocalObjectReference functions
#' @export
LocalObjectReference <- function(name = NULL) {
    structure(list(name = name), class = "gar_LocalObjectReference")
}

#' AutoDomainMappingSpec Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The desired state of the Auto Domain Mapping.
#' 
#' @param forceOverride If set, the mapping will override any mapping set before this spec was set
#' @param expansionType The type of expansion for the auto auto domain mapping
#' @param certificateMode The mode of the certificate
#' 
#' @return AutoDomainMappingSpec object
#' 
#' @family AutoDomainMappingSpec functions
#' @export
AutoDomainMappingSpec <- function(forceOverride = NULL, expansionType = NULL, certificateMode = NULL) {
    structure(list(forceOverride = forceOverride, expansionType = expansionType, 
        certificateMode = certificateMode), class = "gar_AutoDomainMappingSpec")
}

#' ListAutoDomainMappingsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ListAutoDomainMappingsResponse is a list of AutoDomainMapping resources.
#' 
#' @param unreachable Locations that could not be reached
#' @param metadata Metadata associated with this AutoDomainMapping list
#' @param items List of AutoDomainMappings
#' @param apiVersion The API version for this call such as 'serving
#' 
#' @return ListAutoDomainMappingsResponse object
#' 
#' @family ListAutoDomainMappingsResponse functions
#' @export
ListAutoDomainMappingsResponse <- function(unreachable = NULL, metadata = NULL, items = NULL, 
    apiVersion = NULL) {
    structure(list(kind = kind, unreachable = unreachable, metadata = metadata, items = items, 
        apiVersion = apiVersion), class = "gar_ListAutoDomainMappingsResponse")
}

#' ConfigMapKeySelector Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedSelects a key from a ConfigMap.
#' 
#' @param optional (Optional)
#' @param key Cloud Run fully managed: not supported
#' @param name Cloud Run fully managed: not supported
#' @param localObjectReference This field should not be used directly as it is meant to be inlined
#' 
#' @return ConfigMapKeySelector object
#' 
#' @family ConfigMapKeySelector functions
#' @export
ConfigMapKeySelector <- function(optional = NULL, key = NULL, name = NULL, localObjectReference = NULL) {
    structure(list(optional = optional, key = key, name = name, localObjectReference = localObjectReference), 
        class = "gar_ConfigMapKeySelector")
}

#' TestIamPermissionsRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request message for `TestIamPermissions` method.
#' 
#' @param permissions The set of permissions to check for the `resource`
#' 
#' @return TestIamPermissionsRequest object
#' 
#' @family TestIamPermissionsRequest functions
#' @export
TestIamPermissionsRequest <- function(permissions = NULL) {
    structure(list(permissions = permissions), class = "gar_TestIamPermissionsRequest")
}

#' ConfigMapVolumeSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedAdapts a ConfigMap into a volume.The contents of the target ConfigMap's Data field will be presented in avolume as files using the keys in the Data field as the file names, unlessthe items element is populated with specific mappings of keys to paths.
#' 
#' @param optional (Optional)
#' @param name Cloud Run fully managed: not supported
#' @param defaultMode (Optional)
#' @param items (Optional)
#' 
#' @return ConfigMapVolumeSource object
#' 
#' @family ConfigMapVolumeSource functions
#' @export
ConfigMapVolumeSource <- function(optional = NULL, name = NULL, defaultMode = NULL, 
    items = NULL) {
    structure(list(optional = optional, name = name, defaultMode = defaultMode, items = items), 
        class = "gar_ConfigMapVolumeSource")
}

#' StatusDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' StatusDetails is a set of additional properties that MAY be set by theserver to provide additional information about a response. The Reasonfield of a Status object defines what attributes will be set. Clientsmust ignore fields that do not match the defined type of each attribute,and should assume that any attribute may be empty, invalid, or underdefined.
#' 
#' @param name The name attribute of the resource associated with the status StatusReason
#' @param uid UID of the resource
#' @param group The group attribute of the resource associated with the status
#' @param causes The Causes array includes more details associated with the StatusReason
#' @param retryAfterSeconds If specified, the time in seconds before the operation should be retried
#' 
#' @return StatusDetails object
#' 
#' @family StatusDetails functions
#' @export
StatusDetails <- function(name = NULL, uid = NULL, group = NULL, causes = NULL, retryAfterSeconds = NULL) {
    structure(list(name = name, uid = uid, group = group, causes = causes, retryAfterSeconds = retryAfterSeconds, 
        kind = kind), class = "gar_StatusDetails")
}

#' AuditConfig Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Specifies the audit configuration for a service.The configuration determines which permission types are logged, and whatidentities, if any, are exempted from logging.An AuditConfig must have one or more AuditLogConfigs.If there are AuditConfigs for both `allServices` and a specific service,the union of the two AuditConfigs is used for that service: the log_typesspecified in each AuditConfig are enabled, and the exempted_members in eachAuditLogConfig are exempted.Example Policy with multiple AuditConfigs:    {      'audit_configs': [        {          'service': 'allServices'          'audit_log_configs': [            {              'log_type': 'DATA_READ',              'exempted_members': [                'user:jose@example.com'              ]            },            {              'log_type': 'DATA_WRITE',            },            {              'log_type': 'ADMIN_READ',            }          ]        },        {          'service': 'sampleservice.googleapis.com'          'audit_log_configs': [            {              'log_type': 'DATA_READ',            },            {              'log_type': 'DATA_WRITE',              'exempted_members': [                'user:aliya@example.com'              ]            }          ]        }      ]    }For sampleservice, this policy enables DATA_READ, DATA_WRITE and ADMIN_READlogging. It also exempts jose@example.com from DATA_READ logging, andaliya@example.com from DATA_WRITE logging.
#' 
#' @param service Specifies a service that will be enabled for audit logging
#' @param auditLogConfigs The configuration for logging of each type of permission
#' 
#' @return AuditConfig object
#' 
#' @family AuditConfig functions
#' @export
AuditConfig <- function(service = NULL, auditLogConfigs = NULL) {
    structure(list(service = service, auditLogConfigs = auditLogConfigs), class = "gar_AuditConfig")
}

#' StatusCause Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' StatusCause provides more information about an api.Status failure, includingcases when multiple errors are encountered.
#' 
#' @param message A human-readable description of the cause of the error
#' @param reason A machine-readable description of the cause of the error
#' @param field The field of the resource that has caused this error, as named by its JSON
#' 
#' @return StatusCause object
#' 
#' @family StatusCause functions
#' @export
StatusCause <- function(message = NULL, reason = NULL, field = NULL) {
    structure(list(message = message, reason = reason, field = field), class = "gar_StatusCause")
}

#' AuthorizedDomain Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A domain that a user has been authorized to administer. To authorize useof a domain, verify ownership via[Webmaster Central](https://www.google.com/webmasters/verification/home).
#' 
#' @param name Read only
#' @param id Relative name of the domain authorized for use
#' 
#' @return AuthorizedDomain object
#' 
#' @family AuthorizedDomain functions
#' @export
AuthorizedDomain <- function(name = NULL, id = NULL) {
    structure(list(name = name, id = id), class = "gar_AuthorizedDomain")
}

#' Expr Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Represents an expression text. Example:    title: 'User account presence'    description: 'Determines whether the request has a user account'    expression: 'size(request.user) > 0'
#' 
#' @param expression Textual representation of an expression in
#' @param title An optional title for the expression, i
#' @param location An optional string indicating the location of the expression for error
#' @param description An optional description of the expression
#' 
#' @return Expr object
#' 
#' @family Expr functions
#' @export
Expr <- function(expression = NULL, title = NULL, location = NULL, description = NULL) {
    structure(list(expression = expression, title = title, location = location, description = description), 
        class = "gar_Expr")
}

#' ListServicesResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A list of Service resources.
#' 
#' @param apiVersion The API version for this call such as 'serving
#' @param unreachable Locations that could not be reached
#' @param metadata Metadata associated with this Service list
#' @param items List of Services
#' 
#' @return ListServicesResponse object
#' 
#' @family ListServicesResponse functions
#' @export
ListServicesResponse <- function(apiVersion = NULL, unreachable = NULL, metadata = NULL, 
    items = NULL) {
    structure(list(apiVersion = apiVersion, kind = kind, unreachable = unreachable, 
        metadata = metadata, items = items), class = "gar_ListServicesResponse")
}

#' Addressable Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Information for connecting over HTTP(s).
#' 
#' @param url No description
#' 
#' @return Addressable object
#' 
#' @family Addressable functions
#' @export
Addressable <- function(url = NULL) {
    structure(list(url = url), class = "gar_Addressable")
}

#' Volume Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedVolume represents a named volume in a container.
#' 
#' @param name Cloud Run fully managed: not supported
#' @param secret Cloud Run fully managed: not supported
#' @param configMap Cloud Run fully managed: not supported
#' 
#' @return Volume object
#' 
#' @family Volume functions
#' @export
Volume <- function(name = NULL, secret = NULL, configMap = NULL) {
    structure(list(name = name, secret = secret, configMap = configMap), class = "gar_Volume")
}

#' ContainerPort Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedContainerPort represents a network port in a single container.
#' 
#' @param name (Optional)
#' @param containerPort (Optional)
#' @param protocol (Optional)
#' 
#' @return ContainerPort object
#' 
#' @family ContainerPort functions
#' @export
ContainerPort <- function(name = NULL, containerPort = NULL, protocol = NULL) {
    structure(list(name = name, containerPort = containerPort, protocol = protocol), 
        class = "gar_ContainerPort")
}

#' TestIamPermissionsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for `TestIamPermissions` method.
#' 
#' @param permissions A subset of `TestPermissionsRequest
#' 
#' @return TestIamPermissionsResponse object
#' 
#' @family TestIamPermissionsResponse functions
#' @export
TestIamPermissionsResponse <- function(permissions = NULL) {
    structure(list(permissions = permissions), class = "gar_TestIamPermissionsResponse")
}

#' ListConfigurationsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' ListConfigurationsResponse is a list of Configuration resources.
#' 
#' @param unreachable Locations that could not be reached
#' @param metadata Metadata associated with this Configuration list
#' @param items List of Configurations
#' @param apiVersion The API version for this call such as 'serving
#' 
#' @return ListConfigurationsResponse object
#' 
#' @family ListConfigurationsResponse functions
#' @export
ListConfigurationsResponse <- function(unreachable = NULL, metadata = NULL, items = NULL, 
    apiVersion = NULL) {
    structure(list(kind = kind, unreachable = unreachable, metadata = metadata, items = items, 
        apiVersion = apiVersion), class = "gar_ListConfigurationsResponse")
}

#' ServiceStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The current state of the Service. Output only.
#' 
#' @param conditions Conditions communicates information about ongoing/complete
#' @param address From RouteStatus
#' @param observedGeneration ObservedGeneration is the 'Generation' of the Route that
#' @param url From RouteStatus
#' @param traffic From RouteStatus
#' @param latestReadyRevisionName From ConfigurationStatus
#' @param latestCreatedRevisionName From ConfigurationStatus
#' 
#' @return ServiceStatus object
#' 
#' @family ServiceStatus functions
#' @export
ServiceStatus <- function(conditions = NULL, address = NULL, observedGeneration = NULL, 
    url = NULL, traffic = NULL, latestReadyRevisionName = NULL, latestCreatedRevisionName = NULL) {
    structure(list(conditions = conditions, address = address, observedGeneration = observedGeneration, 
        url = url, traffic = traffic, latestReadyRevisionName = latestReadyRevisionName, 
        latestCreatedRevisionName = latestCreatedRevisionName), class = "gar_ServiceStatus")
}

#' EnvFromSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedEnvFromSource represents the source of a set of ConfigMaps
#' 
#' @param configMapRef (Optional)
#' @param secretRef (Optional)
#' @param prefix (Optional)
#' 
#' @return EnvFromSource object
#' 
#' @family EnvFromSource functions
#' @export
EnvFromSource <- function(configMapRef = NULL, secretRef = NULL, prefix = NULL) {
    structure(list(configMapRef = configMapRef, secretRef = secretRef, prefix = prefix), 
        class = "gar_EnvFromSource")
}

#' HTTPGetAction Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedHTTPGetAction describes an action based on HTTP Get requests.
#' 
#' @param path (Optional)
#' @param host (Optional)
#' @param scheme (Optional)
#' @param httpHeaders (Optional)
#' 
#' @return HTTPGetAction object
#' 
#' @family HTTPGetAction functions
#' @export
HTTPGetAction <- function(path = NULL, host = NULL, scheme = NULL, httpHeaders = NULL) {
    structure(list(path = path, host = host, scheme = scheme, httpHeaders = httpHeaders), 
        class = "gar_HTTPGetAction")
}

#' ConfigMapEnvSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Run fully managed: not supportedCloud Run for Anthos: supportedConfigMapEnvSource selects a ConfigMap to populate the environmentvariables with.The contents of the target ConfigMap's Data field will represent thekey-value pairs as environment variables.
#' 
#' @param localObjectReference This field should not be used directly as it is meant to be inlined
#' @param optional (Optional)
#' @param name Cloud Run fully managed: not supported
#' 
#' @return ConfigMapEnvSource object
#' 
#' @family ConfigMapEnvSource functions
#' @export
ConfigMapEnvSource <- function(localObjectReference = NULL, optional = NULL, name = NULL) {
    structure(list(localObjectReference = localObjectReference, optional = optional, 
        name = name), class = "gar_ConfigMapEnvSource")
}

#' RouteSpec Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' RouteSpec holds the desired state of the Route (from the client).
#' 
#' @param traffic Traffic specifies how to distribute traffic over a collection of Knative
#' 
#' @return RouteSpec object
#' 
#' @family RouteSpec functions
#' @export
RouteSpec <- function(traffic = NULL) {
    structure(list(traffic = traffic), class = "gar_RouteSpec")
}

#' OwnerReference Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' OwnerReference contains enough information to let you identify an owningobject. Currently, an owning object must be in the same namespace, so thereis no namespace field.
#' 
#' @param uid UID of the referent
#' @param controller If true, this reference points to the managing controller
#' @param blockOwnerDeletion If true, AND if the owner has the 'foregroundDeletion' finalizer, then
#' @param apiVersion API version of the referent
#' @param name Name of the referent
#' 
#' @return OwnerReference object
#' 
#' @family OwnerReference functions
#' @export
OwnerReference <- function(uid = NULL, controller = NULL, blockOwnerDeletion = NULL, 
    apiVersion = NULL, name = NULL) {
    structure(list(uid = uid, controller = controller, kind = kind, blockOwnerDeletion = blockOwnerDeletion, 
        apiVersion = apiVersion, name = name), class = "gar_OwnerReference")
}


#' Route Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Route is responsible for configuring ingress over a collection of Revisions.Some of the Revisions a Route distributes traffic over may be specified byreferencing the Configuration responsible for creating them; in these casesthe Route is additionally responsible for monitoring the Configuration for'latest ready' revision changes, and smoothly rolling out latest revisions.See also:https://github.com/knative/serving/blob/master/docs/spec/overview.md#routeCloud Run currently supports referencing a single Configuration toautomatically deploy the 'latest ready' Revision from that Configuration.
#' 
#' @param metadata Metadata associated with this Route, including name, namespace, labels,
#' @param status Status communicates the observed state of the Route (from the controller)
#' @param apiVersion The API version for this call such as 'serving
#' @param spec Spec holds the desired state of the Route (from the client)
#' 
#' @return Route object
#' 
#' @family Route functions
#' @export


Route <- function(metadata = NULL, status = NULL, apiVersion = NULL, spec = NULL) {
    
    
    
    structure(list(kind = kind, metadata = metadata, status = status, apiVersion = apiVersion, 
        spec = spec), class = "gar_Route")
}

