#' #' Cloud Scheduler API Objects
#' #' Creates and manages jobs run on a regular recurring schedule.
#' #'
#' #' Auto-generated code by googleAuthR::gar_create_api_objects
#' #'  at 2019-11-04 15:44:38
#' #' filename: R/objs_schedule.R
#' #' api_json: schedule
#' #'
#' #' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton
#'
#' #' AppEngineRouting Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' App Engine Routing.For more information about services, versions, and instances see[An Overview of AppEngine](https://cloud.google.com/appengine/docs/python/an-overview-of-app-engine),[Microservices Architecture on Google AppEngine](https://cloud.google.com/appengine/docs/python/microservices-on-app-engine),[App Engine Standard requestrouting](https://cloud.google.com/appengine/docs/standard/python/how-requests-are-routed),and [App Engine Flex requestrouting](https://cloud.google.com/appengine/docs/flexible/python/how-requests-are-routed).
#' #'
#' #' @param version App version
#' #' @param host Output only
#' #' @param service App service
#' #' @param instance App instance
#' #'
#' #' @return AppEngineRouting object
#' #'
#' #' @family AppEngineRouting functions
#' #' @export
#' AppEngineRouting <- function(version = NULL, host = NULL, service = NULL, instance = NULL) {
#'     structure(list(version = version, host = host, service = service, instance = instance),
#'         class = "gar_AppEngineRouting")
#' }
#'
#' #' Empty Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' A generic empty message that you can re-use to avoid defining duplicatedempty messages in your APIs. A typical example is to use it as the requestor the response type of an API method. For instance:    service Foo {      rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);    }The JSON representation for `Empty` is empty JSON object `{}`.
#' #'
#' #'
#' #'
#' #' @return Empty object
#' #'
#' #' @family Empty functions
#' #' @export
#' Empty <- function() {
#'     list()
#' }
#'
#' #' ListJobsResponse Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Response message for listing jobs using ListJobs.
#' #'
#' #' @param jobs The list of jobs
#' #' @param nextPageToken A token to retrieve next page of results
#' #'
#' #' @return ListJobsResponse object
#' #'
#' #' @family ListJobsResponse functions
#' #' @export
#' ListJobsResponse <- function(jobs = NULL, nextPageToken = NULL) {
#'     structure(list(jobs = jobs, nextPageToken = nextPageToken), class = "gar_ListJobsResponse")
#' }
#'
#' #' AppEngineHttpTarget Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' App Engine target. The job will be pushed to a job handler by meansof an HTTP request via an http_method suchas HTTP POST, HTTP GET, etc. The job is acknowledged by means of anHTTP response code in the range [200 - 299]. Error 503 isconsidered an App Engine system error instead of an applicationerror. Requests returning error 503 will be retried regardless ofretry configuration and not counted against retry counts. Any otherresponse code, or a failure to receive a response before thedeadline, constitutes a failed attempt.
#' #'
#' #' @param AppEngineHttpTarget.headers The \link{AppEngineHttpTarget.headers} object or list of objects
#' #' @param relativeUri The relative URI
#' #' @param headers HTTP request headers
#' #' @param appEngineRouting App Engine Routing setting for the job
#' #' @param httpMethod The HTTP method to use for the request
#' #' @param body Body
#' #'
#' #' @return AppEngineHttpTarget object
#' #'
#' #' @family AppEngineHttpTarget functions
#' #' @export
#' AppEngineHttpTarget <- function(AppEngineHttpTarget.headers = NULL, relativeUri = NULL,
#'     headers = NULL, appEngineRouting = NULL, httpMethod = NULL, body = NULL) {
#'     structure(list(AppEngineHttpTarget.headers = AppEngineHttpTarget.headers, relativeUri = relativeUri,
#'         headers = headers, appEngineRouting = appEngineRouting, httpMethod = httpMethod,
#'         body = body), class = "gar_AppEngineHttpTarget")
#' }
#'
#' #' AppEngineHttpTarget.headers Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' HTTP request headers.This map contains the header field names and values. Headers can be setwhen the job is created.Cloud Scheduler sets some headers to default values:* `User-Agent`: By default, this header is  `'AppEngine-Google; (+http://code.google.com/appengine)'`.  This header can be modified, but Cloud Scheduler will append  `'AppEngine-Google; (+http://code.google.com/appengine)'` to the  modified `User-Agent`.* `X-CloudScheduler`: This header will be set to true.If the job has an body, Cloud Scheduler setsthe following headers:* `Content-Type`: By default, the `Content-Type` header is set to  `'application/octet-stream'`. The default can be overridden by explictly  setting `Content-Type` to a particular media type when the job is  created.  For example, `Content-Type` can be set to `'application/json'`.* `Content-Length`: This is computed by Cloud Scheduler. This value is  output only. It cannot be changed.The headers below are output only. They cannot be set or overridden:* `X-Google-*`: For Google internal use only.* `X-AppEngine-*`: For Google internal use only.In addition, some App Engine headers, which containjob-specific information, are also be sent to the job handler.
#' #'
#' #'
#' #'
#' #' @return AppEngineHttpTarget.headers object
#' #'
#' #' @family AppEngineHttpTarget functions
#' #' @export
#' AppEngineHttpTarget.headers <- function() {
#'     list()
#' }
#'
#' #' Location Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' A resource that represents Google Cloud Platform location.
#' #'
#' #' @param Location.metadata The \link{Location.metadata} object or list of objects
#' #' @param Location.labels The \link{Location.labels} object or list of objects
#' #' @param name Resource name for the location, which may vary between implementations
#' #' @param locationId The canonical id for this location
#' #' @param displayName The friendly name for this location, typically a nearby city name
#' #' @param metadata Service-specific metadata
#' #' @param labels Cross-service attributes for the location
#' #'
#' #' @return Location object
#' #'
#' #' @family Location functions
#' #' @export
#' Location <- function(Location.metadata = NULL, Location.labels = NULL, name = NULL,
#'     locationId = NULL, displayName = NULL, metadata = NULL, labels = NULL) {
#'     structure(list(Location.metadata = Location.metadata, Location.labels = Location.labels,
#'         name = name, locationId = locationId, displayName = displayName, metadata = metadata,
#'         labels = labels), class = "gar_Location")
#' }
#'
#' #' Location.metadata Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Service-specific metadata. For example the available capacity at the givenlocation.
#' #'
#' #'
#' #'
#' #' @return Location.metadata object
#' #'
#' #' @family Location functions
#' #' @export
#' Location.metadata <- function() {
#'     list()
#' }
#'
#' #' Location.labels Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Cross-service attributes for the location. For example    {'cloud.googleapis.com/region': 'us-east1'}
#' #'
#' #'
#' #'
#' #' @return Location.labels object
#' #'
#' #' @family Location functions
#' #' @export
#' Location.labels <- function() {
#'     list()
#' }
#'
#' #' RetryConfig Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Settings that determine the retry behavior.By default, if a job does not complete successfully (meaning thatan acknowledgement is not received from the handler, then it will be retriedwith exponential backoff according to the settings in RetryConfig.
#' #'
#' #' @param maxRetryDuration The time limit for retrying a failed job, measured from time when an
#' #' @param retryCount The number of attempts that the system will make to run a job using the
#' #' @param maxDoublings The time between retries will double `max_doublings` times
#' #' @param minBackoffDuration The minimum amount of time to wait before retrying a job after
#' #' @param maxBackoffDuration The maximum amount of time to wait before retrying a job after
#' #'
#' #' @return RetryConfig object
#' #'
#' #' @family RetryConfig functions
#' #' @export
#' RetryConfig <- function(maxRetryDuration = NULL, retryCount = NULL, maxDoublings = NULL,
#'     minBackoffDuration = NULL, maxBackoffDuration = NULL) {
#'     structure(list(maxRetryDuration = maxRetryDuration, retryCount = retryCount,
#'         maxDoublings = maxDoublings, minBackoffDuration = minBackoffDuration, maxBackoffDuration = maxBackoffDuration),
#'         class = "gar_RetryConfig")
#' }
#'
#' #' ResumeJobRequest Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Request message for ResumeJob.
#' #'
#' #'
#' #'
#' #' @return ResumeJobRequest object
#' #'
#' #' @family ResumeJobRequest functions
#' #' @export
#' ResumeJobRequest <- function() {
#'     list()
#' }
#'
#' #' OidcToken Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Contains information needed for generating an[OpenID Connecttoken](https://developers.google.com/identity/protocols/OpenIDConnect).This type of authorization can be used for many scenarios, includingcalling Cloud Run, or endpoints where you intend to validate the tokenyourself.
#' #'
#' #' @param audience Audience to be used when generating OIDC token
#' #' @param serviceAccountEmail [Service account email](https://cloud
#' #'
#' #' @return OidcToken object
#' #'
#' #' @family OidcToken functions
#' #' @export
#' OidcToken <- function(audience = NULL, serviceAccountEmail = NULL) {
#'     structure(list(audience = audience, serviceAccountEmail = serviceAccountEmail),
#'         class = "gar_OidcToken")
#' }
#'
#' #' ListLocationsResponse Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' The response message for Locations.ListLocations.
#' #'
#' #' @param locations A list of locations that matches the specified filter in the request
#' #' @param nextPageToken The standard List next-page token
#' #'
#' #' @return ListLocationsResponse object
#' #'
#' #' @family ListLocationsResponse functions
#' #' @export
#' ListLocationsResponse <- function(locations = NULL, nextPageToken = NULL) {
#'     structure(list(locations = locations, nextPageToken = nextPageToken), class = "gar_ListLocationsResponse")
#' }
#'
#' #' PubsubTarget Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Pub/Sub target. The job will be delivered by publishing a message tothe given Pub/Sub topic.
#' #'
#' #' @param PubsubTarget.attributes The \link{PubsubTarget.attributes} object or list of objects
#' #' @param data The message payload for PubsubMessage
#' #' @param attributes Attributes for PubsubMessage
#' #' @param topicName Required
#' #'
#' #' @return PubsubTarget object
#' #'
#' #' @family PubsubTarget functions
#' #' @export
#' PubsubTarget <- function(PubsubTarget.attributes = NULL, data = NULL, attributes = NULL,
#'     topicName = NULL) {
#'     structure(list(PubsubTarget.attributes = PubsubTarget.attributes, data = data,
#'         attributes = attributes, topicName = topicName), class = "gar_PubsubTarget")
#' }
#'
#' #' PubsubTarget.attributes Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Attributes for PubsubMessage.Pubsub message must contain either non-empty data, or at least oneattribute.
#' #'
#' #'
#' #'
#' #' @return PubsubTarget.attributes object
#' #'
#' #' @family PubsubTarget functions
#' #' @export
#' PubsubTarget.attributes <- function() {
#'     list()
#' }
#'
#'
#' #' PauseJobRequest Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Request message for PauseJob.
#' #'
#' #'
#' #'
#' #' @return PauseJobRequest object
#' #'
#' #' @family PauseJobRequest functions
#' #' @export
#' PauseJobRequest <- function() {
#'     list()
#' }
#'
#' #' RunJobRequest Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Request message for forcing a job to run now usingRunJob.
#' #'
#' #'
#' #'
#' #' @return RunJobRequest object
#' #'
#' #' @family RunJobRequest functions
#' #' @export
#' RunJobRequest <- function() {
#'     list()
#' }
#'
#' #' OAuthToken Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Contains information needed for generating an[OAuth token](https://developers.google.com/identity/protocols/OAuth2).This type of authorization should generally only be used when calling GoogleAPIs hosted on *.googleapis.com.
#' #'
#' #' @param scope OAuth scope to be used for generating OAuth access token
#' #' @param serviceAccountEmail [Service account email](https://cloud
#' #'
#' #' @return OAuthToken object
#' #'
#' #' @family OAuthToken functions
#' #' @export
#' OAuthToken <- function(scope = NULL, serviceAccountEmail = NULL) {
#'     structure(list(scope = scope, serviceAccountEmail = serviceAccountEmail), class = "gar_OAuthToken")
#' }
#'
#' #' PubsubMessage Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' A message that is published by publishers and consumed by subscribers. Themessage must contain either a non-empty data field or at least one attribute.Note that client libraries represent this object differentlydepending on the language. See the corresponding<a href='https://cloud.google.com/pubsub/docs/reference/libraries'>clientlibrary documentation</a> for more information. See<a href='https://cloud.google.com/pubsub/quotas'>Quotas and limits</a>for more information about message limits.
#' #'
#' #' @param PubsubMessage.attributes The \link{PubsubMessage.attributes} object or list of objects
#' #' @param attributes Optional attributes for this message
#' #' @param messageId ID of this message, assigned by the server when the message is published
#' #' @param publishTime The time at which the message was published, populated by the server when
#' #' @param data The message data field
#' #'
#' #' @return PubsubMessage object
#' #'
#' #' @family PubsubMessage functions
#' #' @export
#' PubsubMessage <- function(PubsubMessage.attributes = NULL, attributes = NULL, messageId = NULL,
#'     publishTime = NULL, data = NULL) {
#'     structure(list(PubsubMessage.attributes = PubsubMessage.attributes, attributes = attributes,
#'         messageId = messageId, publishTime = publishTime, data = data), class = "gar_PubsubMessage")
#' }
#'
#' #' PubsubMessage.attributes Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' Optional attributes for this message.
#' #'
#' #'
#' #'
#' #' @return PubsubMessage.attributes object
#' #'
#' #' @family PubsubMessage functions
#' #' @export
#' PubsubMessage.attributes <- function() {
#'     list()
#' }
#'
#'
#' #' Status Object
#' #'
#' #' @details
#' #' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' #' The `Status` type defines a logical error model that is suitable fordifferent programming environments, including REST APIs and RPC APIs. It isused by [gRPC](https://github.com/grpc). Each `Status` message containsthree pieces of data: error code, error message, and error details.You can find out more about this error model and how to work with it in the[API Design Guide](https://cloud.google.com/apis/design/errors).
#' #'
#' #' @param code The status code, which should be an enum value of google
#' #' @param message A developer-facing error message, which should be in English
#' #' @param details A list of messages that carry the error details
#' #'
#' #' @return Status object
#' #'
#' #' @family Status functions
#' #' @export
#'
#'
#' Status <- function(code = NULL, message = NULL, details = NULL) {
#'
#'
#'
#'     structure(list(code = code, message = message, details = details), class = "gar_Status")
#' }
#'
