#' Cloud Run API
#' Deploy and manage user provided container images that scale automatically based on HTTP traffic.
#'
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2019-11-03 11:19:16
#' filename: R/run.R
#' api_json: cr
#'
#' @details
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' @docType package
#' @name run_googleAuthR
#'
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x))
        rmNullObs(x) else x)
}

#' Lists information about the supported locations for this service.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The resource that owns the locations collection, if applicable
#' @param filter The standard list filter
#' @param pageToken The standard list page token
#' @param pageSize The standard list page size
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.list <- function(name, filter = NULL, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}/locations", name)
    # run.projects.locations.list
    pars = list(filter = filter, pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Gets information about a location.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name Resource name for the location
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Returns permissions that a caller has on the specified Project.There are no permissions required for making this API call.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param TestIamPermissionsRequest The \link{TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family TestIamPermissionsRequest functions
#' @export
projects.locations.services.testIamPermissions <- function(TestIamPermissionsRequest,
    resource) {
    url <- sprintf("https://run.googleapis.com/v1/{+resource}:testIamPermissions",
        resource)
    # run.projects.locations.services.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(TestIamPermissionsRequest, "gar_TestIamPermissionsRequest"))

    f(the_body = TestIamPermissionsRequest)

}

#' Replace a service.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Service The \link{Service} object to pass to this method
#' @param name The name of the service being replaced
#' @importFrom googleAuthR gar_api_generator
#' @family Service functions
#' @export
projects.locations.services.replaceService <- function(Service, name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.services.replaceService
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Service, "gar_Service"))

    f(the_body = Service)

}

#' Delete a service.This will cause the Service to stop serving traffic and will delete thechild entities like Routes, Configurations and Revisions.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the service to delete
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.services.delete <- function(name, apiVersion = NULL, propagationPolicy = NULL,
    kind = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.services.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List services.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the services should be listed
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @param labelSelector Allows to filter resources based on a label
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.services.list <- function(parent, fieldSelector = NULL, resourceVersion = NULL,
    includeUninitialized = NULL, continue = NULL, limit = NULL, watch = NULL, labelSelector = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/services", parent)
    # run.projects.locations.services.list
    pars = list(fieldSelector = fieldSelector, resourceVersion = resourceVersion,
        includeUninitialized = includeUninitialized, continue = continue, limit = limit,
        watch = watch, labelSelector = labelSelector)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Sets the IAM Access control policy for the specified Service. Overwritesany existing policy.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.locations.services.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://run.googleapis.com/v1/{+resource}:setIamPolicy", resource)
    # run.projects.locations.services.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))

    f(the_body = SetIamPolicyRequest)

}

#' Create a service.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Service The \link{Service} object to pass to this method
#' @param parent The namespace in which the service should be created
#' @importFrom googleAuthR gar_api_generator
#' @family Service functions
#' @export
projects.locations.services.create <- function(Service, parent) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/services", parent)
    # run.projects.locations.services.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Service, "gar_Service"))

    f(the_body = Service)

}

#' Get the IAM Access Control policy currently in effect for the givenCloud Run service. This result does not include any inherited policies.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @param options.requestedPolicyVersion Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.services.getIamPolicy <- function(resource, options.requestedPolicyVersion = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+resource}:getIamPolicy", resource)
    # run.projects.locations.services.getIamPolicy
    pars = list(options.requestedPolicyVersion = options.requestedPolicyVersion)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a service.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the service to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.services.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.services.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Replace a route.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Route The \link{Route} object to pass to this method
#' @param name The name of the route being replaced
#' @importFrom googleAuthR gar_api_generator
#' @family Route functions
#' @export
projects.locations.routes.replaceRoute <- function(Route, name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.routes.replaceRoute
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Route, "gar_Route"))

    f(the_body = Route)

}

#' Delete a route.This will cause the route to stop serving traffic.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the route to delete
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.routes.delete <- function(name, apiVersion = NULL, propagationPolicy = NULL,
    kind = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.routes.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List routes.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the routes should be listed
#' @param labelSelector Allows to filter resources based on a label
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param includeUninitialized Not currently used by Cloud Run
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.routes.list <- function(parent, labelSelector = NULL, fieldSelector = NULL,
    includeUninitialized = NULL, resourceVersion = NULL, continue = NULL, limit = NULL,
    watch = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/routes", parent)
    # run.projects.locations.routes.list
    pars = list(labelSelector = labelSelector, fieldSelector = fieldSelector, includeUninitialized = includeUninitialized,
        resourceVersion = resourceVersion, continue = continue, limit = limit, watch = watch)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a route.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the route to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.routes.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.routes.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Create a route.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Route The \link{Route} object to pass to this method
#' @param parent The namespace in which the route should be created
#' @importFrom googleAuthR gar_api_generator
#' @family Route functions
#' @export
projects.locations.routes.create <- function(Route, parent) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/routes", parent)
    # run.projects.locations.routes.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Route, "gar_Route"))

    f(the_body = Route)

}

#' Delete a revision.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the revision to delete
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.revisions.delete <- function(name, apiVersion = NULL, propagationPolicy = NULL,
    kind = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.revisions.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List revisions.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the revisions should be listed
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @param labelSelector Allows to filter resources based on a label
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.revisions.list <- function(parent, continue = NULL, limit = NULL,
    watch = NULL, labelSelector = NULL, resourceVersion = NULL, includeUninitialized = NULL,
    fieldSelector = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/revisions", parent)
    # run.projects.locations.revisions.list
    pars = list(continue = continue, limit = limit, watch = watch, labelSelector = labelSelector,
        resourceVersion = resourceVersion, includeUninitialized = includeUninitialized,
        fieldSelector = fieldSelector)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a revision.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the revision to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.revisions.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.revisions.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' delete a configuration.This will cause the configuration to delete all child revisions. Prior tocalling this, any route referencing the configuration (or revisionfrom the configuration) must be deleted.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the configuration to delete
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.configurations.delete <- function(name, apiVersion = NULL, propagationPolicy = NULL,
    kind = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.configurations.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List configurations.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the configurations should be listed
#' @param labelSelector Allows to filter resources based on a label
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.configurations.list <- function(parent, labelSelector = NULL,
    resourceVersion = NULL, includeUninitialized = NULL, fieldSelector = NULL, continue = NULL,
    limit = NULL, watch = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/configurations", parent)
    # run.projects.locations.configurations.list
    pars = list(labelSelector = labelSelector, resourceVersion = resourceVersion,
        includeUninitialized = includeUninitialized, fieldSelector = fieldSelector,
        continue = continue, limit = limit, watch = watch)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a configuration.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the configuration to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.configurations.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.configurations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Replace a configuration.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Configuration The \link{Configuration} object to pass to this method
#' @param name The name of the configuration being replaced
#' @importFrom googleAuthR gar_api_generator
#' @family Configuration functions
#' @export
projects.locations.configurations.replaceConfiguration <- function(Configuration,
    name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.configurations.replaceConfiguration
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Configuration, "gar_Configuration"))

    f(the_body = Configuration)

}

#' Create a configuration.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Configuration The \link{Configuration} object to pass to this method
#' @param parent The namespace in which the configuration should be created
#' @importFrom googleAuthR gar_api_generator
#' @family Configuration functions
#' @export
projects.locations.configurations.create <- function(Configuration, parent) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/configurations", parent)
    # run.projects.locations.configurations.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Configuration, "gar_Configuration"))

    f(the_body = Configuration)

}

#' Delete a domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the domain mapping to delete
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.domainmappings.delete <- function(name, apiVersion = NULL, propagationPolicy = NULL,
    kind = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.domainmappings.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List domain mappings.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the domain mappings should be listed
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @param labelSelector Allows to filter resources based on a label
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.domainmappings.list <- function(parent, fieldSelector = NULL,
    resourceVersion = NULL, includeUninitialized = NULL, continue = NULL, limit = NULL,
    watch = NULL, labelSelector = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/domainmappings", parent)
    # run.projects.locations.domainmappings.list
    pars = list(fieldSelector = fieldSelector, resourceVersion = resourceVersion,
        includeUninitialized = includeUninitialized, continue = continue, limit = limit,
        watch = watch, labelSelector = labelSelector)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the domain mapping to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.domainmappings.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.domainmappings.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Create a new domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param DomainMapping The \link{DomainMapping} object to pass to this method
#' @param parent The namespace in which the domain mapping should be created
#' @importFrom googleAuthR gar_api_generator
#' @family DomainMapping functions
#' @export
projects.locations.domainmappings.create <- function(DomainMapping, parent) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/domainmappings", parent)
    # run.projects.locations.domainmappings.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(DomainMapping, "gar_DomainMapping"))

    f(the_body = DomainMapping)

}

#' Replace a domain mapping.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param DomainMapping The \link{DomainMapping} object to pass to this method
#' @param name The name of the domain mapping being retrieved
#' @importFrom googleAuthR gar_api_generator
#' @family DomainMapping functions
#' @export
projects.locations.domainmappings.replaceDomainMapping <- function(DomainMapping,
    name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.domainmappings.replaceDomainMapping
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(DomainMapping, "gar_DomainMapping"))

    f(the_body = DomainMapping)

}

#' List authorized domains.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent Name of the parent Application resource
#' @param pageToken Continuation token for fetching the next page of results
#' @param pageSize Maximum results to return per page
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.authorizeddomains.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/authorizeddomains", parent)
    # run.projects.locations.authorizeddomains.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List auto domain mappings.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The project ID or project number from which the auto domain mappings should
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @param labelSelector Allows to filter resources based on a label
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.autodomainmappings.list <- function(parent, watch = NULL, labelSelector = NULL,
    resourceVersion = NULL, includeUninitialized = NULL, fieldSelector = NULL, continue = NULL,
    limit = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/autodomainmappings",
        parent)
    # run.projects.locations.autodomainmappings.list
    pars = list(watch = watch, labelSelector = labelSelector, resourceVersion = resourceVersion,
        includeUninitialized = includeUninitialized, fieldSelector = fieldSelector,
        continue = continue, limit = limit)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about an auto domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the auto domain mapping being retrieved
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.autodomainmappings.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.autodomainmappings.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Creates a new auto domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param AutoDomainMapping The \link{AutoDomainMapping} object to pass to this method
#' @param parent The project ID or project number in which this auto domain mapping should
#' @importFrom googleAuthR gar_api_generator
#' @family AutoDomainMapping functions
#' @export
projects.locations.autodomainmappings.create <- function(AutoDomainMapping, parent) {
    url <- sprintf("https://run.googleapis.com/v1/{+parent}/autodomainmappings",
        parent)
    # run.projects.locations.autodomainmappings.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(AutoDomainMapping, "gar_AutoDomainMapping"))

    f(the_body = AutoDomainMapping)

}

#' Replace an auto domain mapping.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param AutoDomainMapping The \link{AutoDomainMapping} object to pass to this method
#' @param name The name of the auto domain mapping being retrieved
#' @importFrom googleAuthR gar_api_generator
#' @family AutoDomainMapping functions
#' @export
projects.locations.autodomainmappings.replaceAutoDomainMapping <- function(AutoDomainMapping,
    name) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.autodomainmappings.replaceAutoDomainMapping
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(AutoDomainMapping, "gar_AutoDomainMapping"))

    f(the_body = AutoDomainMapping)

}

#' Delete an auto domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the auto domain mapping being deleted
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.autodomainmappings.delete <- function(name, apiVersion = NULL,
    propagationPolicy = NULL, kind = NULL) {
    url <- sprintf("https://run.googleapis.com/v1/{+name}", name)
    # run.projects.locations.autodomainmappings.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Replace a route.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Route The \link{Route} object to pass to this method
#' @param name The name of the route being replaced
#' @importFrom googleAuthR gar_api_generator
#' @family Route functions
#' @export
namespaces.routes.replaceRoute <- function(Route, name) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.routes.replaceRoute
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Route, "gar_Route"))

    f(the_body = Route)

}

#' Delete a route.This will cause the route to stop serving traffic.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the route to delete
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @param apiVersion Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.routes.delete <- function(name, propagationPolicy = NULL, kind = NULL,
    apiVersion = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.routes.delete
    pars = list(propagationPolicy = propagationPolicy, kind = kind, apiVersion = apiVersion)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List routes.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the routes should be listed
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @param labelSelector Allows to filter resources based on a label
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param includeUninitialized Not currently used by Cloud Run
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.routes.list <- function(parent, watch = NULL, labelSelector = NULL, fieldSelector = NULL,
    includeUninitialized = NULL, resourceVersion = NULL, continue = NULL, limit = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+parent}/routes",
        parent)
    # run.namespaces.routes.list
    pars = list(watch = watch, labelSelector = labelSelector, fieldSelector = fieldSelector,
        includeUninitialized = includeUninitialized, resourceVersion = resourceVersion,
        continue = continue, limit = limit)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a route.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the route to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.routes.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.routes.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Create a route.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Route The \link{Route} object to pass to this method
#' @param parent The namespace in which the route should be created
#' @importFrom googleAuthR gar_api_generator
#' @family Route functions
#' @export
namespaces.routes.create <- function(Route, parent) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+parent}/routes",
        parent)
    # run.namespaces.routes.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Route, "gar_Route"))

    f(the_body = Route)

}

#' Delete a revision.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the revision to delete
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @param apiVersion Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.revisions.delete <- function(name, propagationPolicy = NULL, kind = NULL,
    apiVersion = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.revisions.delete
    pars = list(propagationPolicy = propagationPolicy, kind = kind, apiVersion = apiVersion)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List revisions.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the revisions should be listed
#' @param labelSelector Allows to filter resources based on a label
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.revisions.list <- function(parent, labelSelector = NULL, resourceVersion = NULL,
    includeUninitialized = NULL, fieldSelector = NULL, continue = NULL, limit = NULL,
    watch = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+parent}/revisions",
        parent)
    # run.namespaces.revisions.list
    pars = list(labelSelector = labelSelector, resourceVersion = resourceVersion,
        includeUninitialized = includeUninitialized, fieldSelector = fieldSelector,
        continue = continue, limit = limit, watch = watch)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a revision.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the revision to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.revisions.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.revisions.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' delete a configuration.This will cause the configuration to delete all child revisions. Prior tocalling this, any route referencing the configuration (or revisionfrom the configuration) must be deleted.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the configuration to delete
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.configurations.delete <- function(name, apiVersion = NULL, propagationPolicy = NULL,
    kind = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.configurations.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List configurations.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the configurations should be listed
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @param labelSelector Allows to filter resources based on a label
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.configurations.list <- function(parent, continue = NULL, limit = NULL,
    watch = NULL, labelSelector = NULL, resourceVersion = NULL, includeUninitialized = NULL,
    fieldSelector = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+parent}/configurations",
        parent)
    # run.namespaces.configurations.list
    pars = list(continue = continue, limit = limit, watch = watch, labelSelector = labelSelector,
        resourceVersion = resourceVersion, includeUninitialized = includeUninitialized,
        fieldSelector = fieldSelector)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a configuration.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the configuration to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.configurations.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.configurations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Replace a configuration.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Configuration The \link{Configuration} object to pass to this method
#' @param name The name of the configuration being replaced
#' @importFrom googleAuthR gar_api_generator
#' @family Configuration functions
#' @export
namespaces.configurations.replaceConfiguration <- function(Configuration, name) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.configurations.replaceConfiguration
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Configuration, "gar_Configuration"))

    f(the_body = Configuration)

}

#' Create a configuration.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Configuration The \link{Configuration} object to pass to this method
#' @param parent The namespace in which the configuration should be created
#' @importFrom googleAuthR gar_api_generator
#' @family Configuration functions
#' @export
namespaces.configurations.create <- function(Configuration, parent) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+parent}/configurations",
        parent)
    # run.namespaces.configurations.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Configuration, "gar_Configuration"))

    f(the_body = Configuration)

}

#' Delete a domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the domain mapping to delete
#' @param apiVersion Cloud Run currently ignores this parameter
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.domainmappings.delete <- function(name, apiVersion = NULL, propagationPolicy = NULL,
    kind = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+name}",
        name)
    # run.namespaces.domainmappings.delete
    pars = list(apiVersion = apiVersion, propagationPolicy = propagationPolicy, kind = kind)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List domain mappings.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the domain mappings should be listed
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @param labelSelector Allows to filter resources based on a label
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param continue Optional encoded string to continue paging
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.domainmappings.list <- function(parent, limit = NULL, watch = NULL, labelSelector = NULL,
    resourceVersion = NULL, includeUninitialized = NULL, fieldSelector = NULL, continue = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+parent}/domainmappings",
        parent)
    # run.namespaces.domainmappings.list
    pars = list(limit = limit, watch = watch, labelSelector = labelSelector, resourceVersion = resourceVersion,
        includeUninitialized = includeUninitialized, fieldSelector = fieldSelector,
        continue = continue)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the domain mapping to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.domainmappings.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+name}",
        name)
    # run.namespaces.domainmappings.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Create a new domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param DomainMapping The \link{DomainMapping} object to pass to this method
#' @param parent The namespace in which the domain mapping should be created
#' @importFrom googleAuthR gar_api_generator
#' @family DomainMapping functions
#' @export
namespaces.domainmappings.create <- function(DomainMapping, parent) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+parent}/domainmappings",
        parent)
    # run.namespaces.domainmappings.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(DomainMapping, "gar_DomainMapping"))

    f(the_body = DomainMapping)

}

#' Replace a domain mapping.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param DomainMapping The \link{DomainMapping} object to pass to this method
#' @param name The name of the domain mapping being retrieved
#' @importFrom googleAuthR gar_api_generator
#' @family DomainMapping functions
#' @export
namespaces.domainmappings.replaceDomainMapping <- function(DomainMapping, name) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+name}",
        name)
    # run.namespaces.domainmappings.replaceDomainMapping
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(DomainMapping, "gar_DomainMapping"))

    f(the_body = DomainMapping)

}

#' List authorized domains.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent Name of the parent Application resource
#' @param pageToken Continuation token for fetching the next page of results
#' @param pageSize Maximum results to return per page
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.authorizeddomains.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+parent}/authorizeddomains",
        parent)
    # run.namespaces.authorizeddomains.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Creates a new auto domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param AutoDomainMapping The \link{AutoDomainMapping} object to pass to this method
#' @param parent The project ID or project number in which this auto domain mapping should
#' @importFrom googleAuthR gar_api_generator
#' @family AutoDomainMapping functions
#' @export
namespaces.autodomainmappings.create <- function(AutoDomainMapping, parent) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+parent}/autodomainmappings",
        parent)
    # run.namespaces.autodomainmappings.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(AutoDomainMapping, "gar_AutoDomainMapping"))

    f(the_body = AutoDomainMapping)

}

#' Replace an auto domain mapping.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param AutoDomainMapping The \link{AutoDomainMapping} object to pass to this method
#' @param name The name of the auto domain mapping being retrieved
#' @importFrom googleAuthR gar_api_generator
#' @family AutoDomainMapping functions
#' @export
namespaces.autodomainmappings.replaceAutoDomainMapping <- function(AutoDomainMapping,
    name) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+name}",
        name)
    # run.namespaces.autodomainmappings.replaceAutoDomainMapping
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(AutoDomainMapping, "gar_AutoDomainMapping"))

    f(the_body = AutoDomainMapping)

}

#' Delete an auto domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the auto domain mapping being deleted
#' @param propagationPolicy Specifies the propagation policy of delete
#' @param kind Cloud Run currently ignores this parameter
#' @param apiVersion Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.autodomainmappings.delete <- function(name, propagationPolicy = NULL,
    kind = NULL, apiVersion = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+name}",
        name)
    # run.namespaces.autodomainmappings.delete
    pars = list(propagationPolicy = propagationPolicy, kind = kind, apiVersion = apiVersion)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' List auto domain mappings.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The project ID or project number from which the auto domain mappings should
#' @param labelSelector Allows to filter resources based on a label
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param includeUninitialized Not currently used by Cloud Run
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.autodomainmappings.list <- function(parent, labelSelector = NULL, resourceVersion = NULL,
    includeUninitialized = NULL, fieldSelector = NULL, continue = NULL, limit = NULL,
    watch = NULL) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+parent}/autodomainmappings",
        parent)
    # run.namespaces.autodomainmappings.list
    pars = list(labelSelector = labelSelector, resourceVersion = resourceVersion,
        includeUninitialized = includeUninitialized, fieldSelector = fieldSelector,
        continue = continue, limit = limit, watch = watch)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about an auto domain mapping.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the auto domain mapping being retrieved
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.autodomainmappings.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/apis/domains.cloudrun.com/v1/{+name}",
        name)
    # run.namespaces.autodomainmappings.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' List services.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param parent The namespace from which the services should be listed
#' @param labelSelector Allows to filter resources based on a label
#' @param fieldSelector Allows to filter resources based on a specific value for a field name
#' @param includeUninitialized Not currently used by Cloud Run
#' @param resourceVersion The baseline resource version from which the list or watch operation should
#' @param continue Optional encoded string to continue paging
#' @param limit The maximum number of records that should be returned
#' @param watch Flag that indicates that the client expects to watch this resource as well
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.services.list <- function(parent, labelSelector = NULL, fieldSelector = NULL,
    includeUninitialized = NULL, resourceVersion = NULL, continue = NULL, limit = NULL,
    watch = NULL) {

    endpoint <- "https://europe-west1-run.googleapis.com"
    url <- sprintf("%s/apis/serving.knative.dev/v1/namespaces/%s/services",
        endpoint,parent)
    # run.namespaces.services.list
    pars = list(labelSelector = labelSelector, fieldSelector = fieldSelector, includeUninitialized = includeUninitialized,
        resourceVersion = resourceVersion, continue = continue, limit = limit, watch = watch)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get information about a service.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the service to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
namespaces.services.get <- function(name) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.services.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Create a service.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Service The \link{Service} object to pass to this method
#' @param parent The namespace in which the service should be created
#' @importFrom googleAuthR gar_api_generator
#' @family Service functions
#' @export
namespaces.services.create <- function(Service, parent) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+parent}/services",
        parent)
    # run.namespaces.services.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Service, "gar_Service"))

    f(the_body = Service)

}

#' Replace a service.Only the spec and metadata labels and annotations are modifiable. Afterthe Update request, Cloud Run will work to make the 'status'match the requested 'spec'.May provide metadata.resourceVersion to enforce update from last read foroptimistic concurrency control.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Service The \link{Service} object to pass to this method
#' @param name The name of the service being replaced
#' @importFrom googleAuthR gar_api_generator
#' @family Service functions
#' @export
namespaces.services.replaceService <- function(Service, name) {
    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.services.replaceService
    f <- googleAuthR::gar_api_generator(url, "PUT", data_parse_function = function(x) x)
    stopifnot(inherits(Service, "gar_Service"))

    f(the_body = Service)

}


#' Delete a service.This will cause the Service to stop serving traffic and will delete thechild entities like Routes, Configurations and Revisions.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://cloud.google.com/run/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param name The name of the service to delete

#' @param propagationPolicy Specifies the propagation policy of delete

#' @param kind Cloud Run currently ignores this parameter

#' @param apiVersion Cloud Run currently ignores this parameter
#' @importFrom googleAuthR gar_api_generator
#' @export


namespaces.services.delete <- function(name, propagationPolicy = NULL, kind = NULL,
    apiVersion = NULL) {


    url <- sprintf("https://run.googleapis.com/apis/serving.knative.dev/v1/{+name}",
        name)
    # run.namespaces.services.delete
    pars = list(propagationPolicy = propagationPolicy, kind = kind, apiVersion = apiVersion)

    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)

    f()


}



